const { stocks, updated, priceLabel } = window.JSE_DASHBOARD_DATA;
const STORAGE_KEY='dailyJseTrackedTickersV2';
const UNIVERSE_URL='https://raw.githubusercontent.com/kbuckle10/jse-main-market-dashboard/main/data.json';
const state={filter:'all',sort:'rank',view:'table',tracked:new Set(),universe:[],watchlistFilter:'all',watchlistExpanded:false};
const $=id=>document.getElementById(id);
const tableBody=$('stockTableBody'),cardView=$('cardView'),tableView=$('tableView'),movementList=$('movementList'),rankingList=$('rankingList'),allocationBar=$('allocationBar'),allocationLegend=$('allocationLegend'),tickerSearch=$('tickerSearch'),tickerSearchResults=$('tickerSearchResults'),watchlistStatusFilter=$('watchlistStatusFilter'),showAllTickersBtn=$('showAllTickersBtn');
const fmt=(v,d=2)=>v==null||Number.isNaN(Number(v))?'N/A':Number(v).toFixed(d);
const pct=v=>v==null?'<span class="neutral">N/A</span>':`<span class="${v>0?'positive':v<0?'negative':'neutral'}">${v>0?'+':''}${fmt(v,1)}%</span>`;
const money=v=>v==null?'N/A':`J$${fmt(v,2)}`;
const dividendMoney=s=>s.latestDividend==null?'N/A':`${s.latestDividendCurrency==='TTD'?'TT$':s.latestDividendCurrency==='USD'?'US$':'J$'}${fmt(s.latestDividend,2)}`;
const dateValue=v=>{const d=new Date(v);return Number.isNaN(d.valueOf())?0:d.valueOf();};
const dividendEventDate=e=>Math.max(dateValue(e?.exDate),dateValue(e?.recordDate),dateValue(e?.payDate));
const currentDividendEvent=s=>{const base={exDate:s.exDate,recordDate:s.recordDate,payDate:s.payDate};const sa=s.saLatestDividend;const crossListed=s.primaryListing?.market&&String(s.primaryListing.market).toUpperCase()!=='JMSE';return !crossListed&&sa&&dividendEventDate(sa)>dividendEventDate(base)?sa:base;};
const dividendDates=s=>{const e=currentDividendEvent(s);return `<small>Ex: ${e.exDate||'N/A'}<br>Rec: ${e.recordDate||'N/A'}<br>Pay: ${e.payDate||'N/A'}</small>`;};
const day=s=>s.dayPct==null?'<span class="neutral">N/A</span>':`<span class="${s.dayPct>0?'positive':s.dayPct<0?'negative':'neutral'}">${s.dayJmd>0?'+':''}${money(s.dayJmd)} / ${s.dayPct>0?'+':''}${fmt(s.dayPct,2)}%</span>`;
const isBigMover=s=>Math.abs(s.dayPct||0)>=5||Math.abs(s.m1||0)>=5||Math.abs(s.ytd||0)>=10||Math.abs(s.m3||0)>=10||Math.abs(s.m6||0)>=10||Math.abs(s.y1||0)>=20;
const detailedMap=()=>new Map(stocks.map(s=>[s.ticker,s]));
function dataState(status){if(status==='scraper-error'||status==='validation-error')return '<span class="negative">ERROR</span>';if(status==='not-found')return '<span class="neutral">N/A</span>';if(status==='validation-warning'||status==='price-missing'||status==='partial')return '<span class="amber">CHECK</span>';return null;}
function yieldDisplay(s){const stateLabel=dataState(s.dividendDataStatus);if(s.trailingYield!=null)return `${fmt(s.trailingYield,2)}%${stateLabel?` <small>${stateLabel}</small>`:''}`;return stateLabel||'<span class="neutral">N/A</span>';}
function latestDividendLink(s){const stateLabel=dataState(s.latestDividendDataStatus);if(s.latestDividend==null)return stateLabel||'<span class="neutral">N/A</span>';const href=s.dividendUrl||`https://www.jamstockex.com/?tag=${encodeURIComponent(s.ticker)}`;return `<a class="dividend-link" href="${href}" target="_blank" rel="noreferrer">${dividendMoney(s)} ↗</a>${stateLabel?` <small>${stateLabel}</small>`:''}`;}
function trackedStocks(){return stocks.filter(s=>state.tracked.has(s.ticker));}function pendingTickers(){const map=detailedMap();return [...state.tracked].filter(t=>!map.has(t));}
function loadWatchlist(){let saved;try{saved=JSON.parse(localStorage.getItem(STORAGE_KEY));}catch{saved=null;}state.tracked=new Set(Array.isArray(saved)?saved.map(t=>String(t).toUpperCase()).filter(Boolean):[]);if(!Array.isArray(saved))localStorage.setItem(STORAGE_KEY,'[]');}
async function loadUniverse(){try{const r=await fetch(UNIVERSE_URL,{cache:'no-store'});if(!r.ok)throw new Error(String(r.status));const d=await r.json();state.universe=(d.stocks||[]).map(s=>({ticker:String(s.ticker||'').toUpperCase(),company:s.company||s.ticker,sector:s.sector||'Other',price:s.price??null,rating:s.rating||'N/A',trailingYield:s.divYield??null,sa:`https://stockanalysis.com/quote/jmse/${encodeURIComponent(s.ticker)}/`,jse:s.jseUrl||`https://www.jamstockex.com/?s=${encodeURIComponent(s.ticker)}`})).filter(s=>s.ticker);}catch{state.universe=stocks.map(s=>({...s}));}}
function saveWatchlist(){localStorage.setItem(STORAGE_KEY,JSON.stringify([...state.tracked]));}
const finite=(v,fallback=null)=>Number.isFinite(Number(v))?Number(v):fallback;
function ratingTier(s){const r=String(s.rating||'').toLowerCase();if(r.includes('strong buy'))return 5;if(r.includes('buy'))return 4;if(r.includes('hold'))return 3;if(r.includes('watch'))return 2;if(r.includes('avoid')||r.includes('sell'))return 1;return 0;}
function entryAdjustment(s){return s.zoneStatus==='below'?12:s.zoneStatus==='in'?7:s.zoneStatus==='above'?-10:0;}
function investorOpportunityScore(s){return Math.max(0,Math.min(120,(finite(s.score,50))+entryAdjustment(s)));}
function investorCompare(a,b){const tier=ratingTier(b)-ratingTier(a);if(tier)return tier;const opportunity=investorOpportunityScore(b)-investorOpportunityScore(a);if(opportunity)return opportunity;const y=(finite(b.trailingYield,-1)-finite(a.trailingYield,-1));if(y)return y;return String(a.ticker).localeCompare(String(b.ticker));}
function ensureSortOptions(){const select=$('sortSelect');if(!select)return;const selected=state.sort;select.innerHTML='<option value="rank">Investor rank: best opportunity</option><option value="rating-desc">Rating: Strong Buy → Avoid</option><option value="score-desc">Research score: high to low</option><option value="zone-best">Entry zone: below/in/above</option><option value="yield-desc">Yield: high to low</option><option value="pe-asc">P/E: low to high</option><option value="pb-asc">P/B: low to high</option><option value="eps-growth-desc">EPS growth: high to low</option><option value="month-desc">1M move: high to low</option><option value="ytd-desc">YTD move: high to low</option><option value="year-desc">1Y move: high to low</option><option value="price-asc">Price: low to high</option><option value="ticker">Ticker A–Z</option>';select.value=selected;select.title='Investor rank prioritizes rating first, then research score adjusted for current buy-zone position. A Hold cannot outrank a Buy.';}
function filteredStocks(){let r=trackedStocks();if(state.filter==='buy')r=r.filter(s=>s.ratingClass==='buy');if(state.filter==='zone')r=r.filter(s=>s.zoneStatus==='in');if(state.filter==='income')r=r.filter(s=>(s.trailingYield||0)>=3);if(state.filter==='movement')r=r.filter(isBigMover);if(state.filter==='dividend')r=r.filter(s=>!/No new declaration/i.test(s.dividendStatus));const zoneRank=s=>s.zoneStatus==='below'?0:s.zoneStatus==='in'?1:s.zoneStatus==='above'?2:3;const sorts={rank:investorCompare,'rating-desc':(a,b)=>ratingTier(b)-ratingTier(a)||investorOpportunityScore(b)-investorOpportunityScore(a),'score-desc':(a,b)=>finite(b.score,-1)-finite(a.score,-1)||investorCompare(a,b),'zone-best':(a,b)=>zoneRank(a)-zoneRank(b)||investorCompare(a,b),'yield-desc':(a,b)=>finite(b.trailingYield,-1)-finite(a.trailingYield,-1),'pe-asc':(a,b)=>finite(a.pe,Infinity)-finite(b.pe,Infinity),'pb-asc':(a,b)=>finite(a.pb,Infinity)-finite(b.pb,Infinity),'eps-growth-desc':(a,b)=>finite(b.epsGrowth,-Infinity)-finite(a.epsGrowth,-Infinity),'price-asc':(a,b)=>finite(a.price,Infinity)-finite(b.price,Infinity),'month-desc':(a,b)=>finite(b.m1,-Infinity)-finite(a.m1,-Infinity),'ytd-desc':(a,b)=>finite(b.ytd,-Infinity)-finite(a.ytd,-Infinity),'year-desc':(a,b)=>finite(b.y1,-Infinity)-finite(a.y1,-Infinity),ticker:(a,b)=>a.ticker.localeCompare(b.ticker)};return r.sort(sorts[state.sort]||investorCompare);}
function buyZoneText(s){if(s.buyLow==null||s.buyHigh==null)return '<span class="neutral">N/A</span>';const yields=s.buyYieldLow!=null&&s.buyYieldHigh!=null?`<br><small>${fmt(s.buyYieldLow,1)}–${fmt(s.buyYieldHigh,1)}% implied</small>`:'';const label=s.zoneStatus==='in'?'IN ZONE':s.zoneStatus==='below'?'BELOW ZONE':'ABOVE ZONE';return `<strong>J$${fmt(s.buyLow,2)}–${fmt(s.buyHigh,2)}</strong>${yields}<br><span class="zone-status ${s.zoneStatus}">${label}</span>`;}
function stockRow(s){return `<tr><td><div class="ticker-wrap"><div style="display:flex;gap:4px"><a class="source-dot" href="${s.jse}" target="_blank">JSE</a><a class="source-dot" href="${s.sa}" target="_blank">SA</a></div><div><div class="ticker">${s.ticker}</div><div class="company">${s.company}</div></div></div></td><td><strong>${money(s.price)}</strong><br><small>${s.priceDate}</small></td><td>${day(s)}</td><td>${pct(s.w1)}</td><td>${pct(s.m1)}</td><td>${pct(s.ytd)}</td><td>${pct(s.m3)}</td><td>${pct(s.m6)}</td><td>${pct(s.y1)}</td><td>${money(s.ttmDps)}</td><td>${yieldDisplay(s)}</td><td><strong>${latestDividendLink(s)}</strong><br><small>${s.dividendStatus||''}</small></td><td>${dividendDates(s)}</td><td><span class="rating ${s.ratingClass}">${s.rating}</span><br><small>${s.reason}</small></td><td>${buyZoneText(s)}</td></tr>`;}
function stockCard(s){return `<article class="stock-card"><div class="card-top"><div><h3>${s.ticker}</h3><div class="company">${s.company}</div></div><span class="rating ${s.ratingClass}">${s.rating}</span></div><div class="price">${money(s.price)}</div><div>${day(s)} <span class="neutral">• ${s.priceDate}</span></div>${[['1 Week',s.w1],['1 Month',s.m1],['YTD',s.ytd],['3 Months',s.m3],['6 Months',s.m6],['12 Months',s.y1]].map(([l,v])=>`<div class="metric-row"><span>${l}</span><strong>${pct(v)}</strong></div>`).join('')}<div class="metric-row"><span>Trailing yield</span><strong>${yieldDisplay(s)}</strong></div><div class="metric-row"><span>Latest dividend</span><strong>${latestDividendLink(s)}</strong></div><div class="metric-row"><span>Target buy zone</span><div>${buyZoneText(s)}</div></div><p class="rank-reason">${s.reason}</p><div class="card-links"><a href="${s.jse}" target="_blank">JSE ↗</a><a href="${s.sa}" target="_blank">StockAnalysis ↗</a></div></article>`;}
function render(){const d=filteredStocks();tableBody.innerHTML=d.map(stockRow).join('')||'<tr><td colspan="15" class="neutral">No tickers selected.</td></tr>';cardView.innerHTML=d.map(stockCard).join('')||'<div class="panel">No tickers selected.</div>';document.querySelectorAll('.filter-tile').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.filter));}
function renderSummary(){const t=trackedStocks(),p=pendingTickers();$('updatedPill').textContent=`${priceLabel} • ${updated}`;$('trackedCount').textContent=state.tracked.size;$('managerTrackedCount').textContent=state.tracked.size;$('buyCount').textContent=t.filter(s=>s.ratingClass==='buy').length;$('zoneCount').textContent=t.filter(s=>s.zoneStatus==='in').length;$('incomeCount').textContent=t.filter(s=>(s.trailingYield||0)>=3).length;$('moveCount').textContent=t.filter(isBigMover).length;$('dividendCount').textContent=t.filter(s=>!/No new declaration/i.test(s.dividendStatus)).length;$('subtitleTickers').textContent=state.tracked.size?[...state.tracked].join(' • ')+(p.length?` • ${p.length} awaiting detailed data`:''):'No tickers selected — build your hand-picked watchlist below';}
function normalizedAllocations(d){const total=d.reduce((sum,s)=>sum+Math.max(Number(s.allocation)||0,0),0);if(!total)return [];return d.map(s=>({...s,normalizedAllocation:((Number(s.allocation)||0)/total)*100}));}
function movementChip(label,value){return value==null?'':`<span class="movement-chip"><small>${label}</small>${pct(value)}</span>`;}
function renderAnalysis(){const t=trackedStocks(),m=t.filter(isBigMover);movementList.innerHTML=m.length?m.map(s=>`<article class="movement-item"><div class="movement-head"><div><strong>${s.ticker}</strong><span>${s.company||''}</span></div><span class="rating ${s.ratingClass}">${s.rating}</span></div><div class="movement-metrics">${movementChip('Day',s.dayPct)}${movementChip('1M',s.m1)}${movementChip('3M',s.m3)}${movementChip('12M',s.y1)}</div><p>${s.reason}</p></article>`).join(''):'<p class="neutral movement-empty">No selected stock currently exceeds the movement thresholds.</p>';rankingList.innerHTML=[...t].sort(investorCompare).map((s,i)=>`<div class="rank-row"><div class="rank-left"><span class="rank-number">${i+1}</span><div><strong>${s.ticker}</strong><div class="rank-reason">${s.reason}</div><small>Research ${fmt(s.score,0)}/100 • ${s.zoneStatus==='below'?'Below buy zone':s.zoneStatus==='in'?'In buy zone':s.zoneStatus==='above'?'Above buy zone':'Zone N/A'} • opportunity ${fmt(investorOpportunityScore(s),0)}</small></div></div><span class="rating ${s.ratingClass}">${s.rating}</span></div>`).join('')||'<p class="neutral">Add tickers to build your Fresh Capital ranking.</p>';const eligible=t.filter(s=>s.ratingClass==='buy'&&Number(s.allocation)>0);const a=normalizedAllocations([...eligible].sort((x,y)=>(y.allocation||0)-(x.allocation||0))),colors=['var(--viz1,#5b8cff)','var(--viz2,#48d7a0)','var(--viz3,#ffd166)','var(--viz4,#9f7aea)','var(--viz5,#38bdf8)','var(--viz6,#fb7185)'];allocationBar.innerHTML=a.map((s,i)=>`<div class="allocation-segment" title="${s.ticker} ${fmt(s.normalizedAllocation,1)}%" style="width:${s.normalizedAllocation}%;background:${colors[i%colors.length]}"></div>`).join('');allocationLegend.innerHTML=a.map((s,i)=>`<div class="legend-item"><span class="legend-dot" style="background:${colors[i%colors.length]}"></span><strong>${s.ticker}</strong> ${fmt(s.normalizedAllocation,1)}%</div>`).join('')||'<span class="neutral">No Buy-rated tracked stocks are currently eligible for new-money allocation.</span>';}
function searchableUniverse(){const m=new Map();for(const u of state.universe)m.set(u.ticker,u);for(const s of stocks)m.set(s.ticker,{...m.get(s.ticker),...s});return [...m.values()];}
function renderTickerSearch(){
  const q=tickerSearch.value.trim().toLowerCase();
  const status=state.watchlistFilter;
  const shouldRender=Boolean(q)||state.watchlistExpanded||status!=='all';
  if(showAllTickersBtn){showAllTickersBtn.textContent=state.watchlistExpanded?'Collapse':'Show all';showAllTickersBtn.setAttribute('aria-expanded',String(state.watchlistExpanded));}
  if(!shouldRender){tickerSearchResults.innerHTML='<p class="ticker-search-hint">Search the full JSE Main Market universe and add only the stocks you want.</p>';return;}
  let matches=searchableUniverse();
  if(q)matches=matches.filter(s=>s.ticker.toLowerCase().includes(q)||String(s.company||'').toLowerCase().includes(q));
  if(status==='tracked')matches=matches.filter(s=>state.tracked.has(s.ticker));
  if(status==='untracked')matches=matches.filter(s=>!state.tracked.has(s.ticker));
  matches.sort((a,b)=>a.ticker.localeCompare(b.ticker));
  if(!matches.length){tickerSearchResults.innerHTML=`<p class="ticker-search-hint">No ${status==='all'?'matching':status} tickers found.</p>`;return;}
  tickerSearchResults.innerHTML=matches.map(s=>{const active=state.tracked.has(s.ticker);return `<div class="ticker-result ${active?'is-tracked':'is-untracked'}"><div class="ticker-result-main"><strong>${s.ticker}</strong><span>${s.company||''}</span><small>${money(s.price)} • ${s.rating||'Analysis pending'}</small></div><div class="ticker-result-actions"><a class="analyze-action" href="${s.sa||`https://stockanalysis.com/quote/jmse/${s.ticker}/`}" target="_blank">Analyze ↗</a><button type="button" class="track-toggle ${active?'remove':'add'}" data-ticker="${s.ticker}">${active?'Remove':'+ Add'}</button></div></div>`;}).join('');
}
function refreshAll(){renderSummary();renderAnalysis();render();renderTickerSearch();}function toggleTracked(t){state.tracked.has(t)?state.tracked.delete(t):state.tracked.add(t);saveWatchlist();refreshAll();}
document.querySelectorAll('.filter-tile').forEach(b=>b.addEventListener('click',()=>{state.filter=b.dataset.filter;render();}));$('sortSelect').addEventListener('change',e=>{state.sort=e.target.value;render();});$('tableViewBtn').addEventListener('click',()=>{tableView.classList.remove('hidden');cardView.classList.add('hidden');});$('cardViewBtn').addEventListener('click',()=>{tableView.classList.add('hidden');cardView.classList.remove('hidden');});tickerSearch.addEventListener('input',()=>renderTickerSearch());if(watchlistStatusFilter)watchlistStatusFilter.addEventListener('change',e=>{state.watchlistFilter=e.target.value;renderTickerSearch();});if(showAllTickersBtn)showAllTickersBtn.addEventListener('click',()=>{state.watchlistExpanded=!state.watchlistExpanded;renderTickerSearch();});tickerSearchResults.addEventListener('click',e=>{const b=e.target.closest('[data-ticker]');if(b)toggleTracked(b.dataset.ticker);});$('resetTrackedBtn').addEventListener('click',()=>{state.tracked.clear();saveWatchlist();refreshAll();});$('themeToggle').addEventListener('click',()=>{const root=document.documentElement,next=root.dataset.theme==='dark'?'light':'dark';root.dataset.theme=next;$('themeToggle').textContent=next==='dark'?'☀':'☾';});async function init(){ensureSortOptions();loadWatchlist();refreshAll();await loadUniverse();renderTickerSearch();}init().catch(console.error);
