window.JSE_DASHBOARD_DATA = {
  "updated": "August 20, 2026",
  "priceLabel": "JSE official close where available / StockAnalysis delayed fallback",
  "stocks": [
    {
      "rank": 1,
      "ticker": "GK",
      "company": "GraceKennedy Limited",
      "price": 76.29,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.24,
      "dayPct": 1.65,
      "w1": -1.04,
      "m1": 6.53,
      "m3": 5.37,
      "m6": 5.1,
      "y1": 8.09,
      "performanceSource": "SA",
      "ttmDps": 2.37,
      "trailingYield": 3.11,
      "forwardYield": null,
      "latestDividend": 0.7,
      "exDate": "Upcoming",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 21, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Strong Buy",
      "ratingClass": "buy",
      "reason": "Best overall mix of business quality, sensible valuation and dividend coverage.",
      "buyLow": 70,
      "buyHigh": 76,
      "buyYieldLow": 3.12,
      "buyYieldHigh": 3.39,
      "zoneStatus": "above",
      "allocation": 16,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=55",
      "dividendUrl": "https://www.jamstockex.com/?tag=GK",
      "sa": "https://stockanalysis.com/quote/jmse/GK/",
      "source": "JSE",
      "ytd": 4.03,
      "volume": 477221
    },
    {
      "rank": 2,
      "ticker": "SJ",
      "company": "Sagicor Group Jamaica Limited",
      "price": 41.06,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.11,
      "dayPct": 0.27,
      "w1": -3.72,
      "m1": 3.35,
      "m3": -3.77,
      "m6": 0.25,
      "y1": -2.2,
      "performanceSource": "SA",
      "ttmDps": 1.78,
      "trailingYield": 4.34,
      "forwardYield": null,
      "latestDividend": 0.89,
      "exDate": "Apr 14, 2026",
      "recordDate": "Apr 14, 2026",
      "payDate": "May 6, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Strong dividend history and attractive actual trailing income support accumulation near the buy-zone ceiling, though recent earnings softness warrants monitoring.",
      "buyLow": 36,
      "buyHigh": 41,
      "buyYieldLow": 4.34,
      "buyYieldHigh": 4.94,
      "zoneStatus": "above",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=297",
      "dividendUrl": "https://www.jamstockex.com/?tag=SJ",
      "sa": "https://stockanalysis.com/quote/jmse/SJ/",
      "source": "JSE",
      "ytd": -3.33,
      "volume": 28579
    },
    {
      "rank": 3,
      "ticker": "SEP",
      "company": "Seprod Limited",
      "price": 74.82,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.55,
      "dayPct": 2.12,
      "w1": 0.81,
      "m1": 2.73,
      "m3": -8.55,
      "m6": -7.42,
      "y1": -2.64,
      "performanceSource": "SA",
      "ttmDps": 1.82,
      "trailingYield": 2.43,
      "forwardYield": null,
      "latestDividend": 0.605,
      "exDate": "May 15, 2026",
      "recordDate": "May 15, 2026",
      "payDate": "Jun 5, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Low payout and strong earnings capacity support selective buying, but the price is at the upper edge of the accumulation range.",
      "buyLow": 68,
      "buyHigh": 75,
      "buyYieldLow": 2.43,
      "buyYieldHigh": 2.68,
      "zoneStatus": "in",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=137",
      "dividendUrl": "https://www.jamstockex.com/?tag=SEP",
      "sa": "https://stockanalysis.com/quote/jmse/SEP/",
      "source": "JSE",
      "ytd": -10.7,
      "volume": 106829
    },
    {
      "rank": 4,
      "ticker": "NCBFG",
      "company": "NCB Financial Group Limited",
      "price": 71.29,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.78,
      "dayPct": 1.11,
      "w1": -2.39,
      "m1": -2.61,
      "m3": 36.67,
      "m6": 63.22,
      "y1": 73.17,
      "performanceSource": "SA",
      "ttmDps": 2,
      "trailingYield": 2.81,
      "forwardYield": null,
      "latestDividend": 0.5,
      "exDate": "Aug 28, 2026",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 11, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "The pullback improves entry value while the current dividend remains comfortably covered relative to the recovery in profitability.",
      "buyLow": 64,
      "buyHigh": 70,
      "buyYieldLow": 2.86,
      "buyYieldHigh": 3.13,
      "zoneStatus": "above",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600012",
      "dividendUrl": "https://www.jamstockex.com/?tag=NCBFG",
      "sa": "https://stockanalysis.com/quote/jmse/NCBFG/",
      "source": "JSE",
      "ytd": 97.22,
      "volume": 51695
    },
    {
      "rank": 5,
      "ticker": "CAR",
      "company": "Carreras Limited",
      "price": 34.94,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.55,
      "dayPct": 4.64,
      "w1": 0,
      "m1": 6.83,
      "m3": 46.99,
      "m6": 63.37,
      "y1": 91.86,
      "performanceSource": "SA",
      "ttmDps": 1.35,
      "trailingYield": 3.86,
      "forwardYield": null,
      "latestDividend": 0.41,
      "exDate": "Aug 28, 2026",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 17, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Strong current income, but a high payout and sharp recent rerating argue against chasing above the dividend buy zone.",
      "buyLow": 29,
      "buyHigh": 32,
      "buyYieldLow": 4.22,
      "buyYieldHigh": 4.66,
      "zoneStatus": "above",
      "allocation": 11,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=39",
      "dividendUrl": "https://www.jamstockex.com/?tag=CAR",
      "sa": "https://stockanalysis.com/quote/jmse/CAR/",
      "source": "JSE",
      "ytd": 83.33,
      "volume": 148878
    },
    {
      "rank": 6,
      "ticker": "LASM",
      "company": "Lasco Manufacturing Limited",
      "price": 8.15,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.04,
      "dayPct": -0.49,
      "w1": 5.12,
      "m1": 24.39,
      "m3": 20.74,
      "m6": 29.29,
      "y1": 36.61,
      "performanceSource": "SA",
      "ttmDps": 0.19,
      "trailingYield": 2.33,
      "forwardYield": null,
      "latestDividend": 0.2,
      "exDate": "Aug 14, 2026",
      "recordDate": "Aug 14, 2026",
      "payDate": "Aug 28, 2026",
      "dividendStatus": "Dividend increased 5.3% YoY",
      "rating": "Hold / Buy dips",
      "ratingClass": "hold",
      "reason": "The dividend increased and coverage is strong, but a 23% one-month rally leaves the share price materially above the preferred income entry zone.",
      "buyLow": 6.25,
      "buyHigh": 7,
      "buyYieldLow": 2.71,
      "buyYieldHigh": 3.04,
      "zoneStatus": "above",
      "allocation": 8,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=103",
      "dividendUrl": "https://www.jamstockex.com/?tag=LASM",
      "sa": "https://stockanalysis.com/quote/jmse/LASM/",
      "source": "JSE",
      "ytd": 42.04,
      "volume": 600640
    },
    {
      "rank": 7,
      "ticker": "KW",
      "company": "Kingston Wharves Limited",
      "price": 33.94,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.06,
      "dayPct": -0.18,
      "w1": 0.89,
      "m1": -3.55,
      "m3": -8.11,
      "m6": -2.86,
      "y1": 9.5,
      "performanceSource": "SA",
      "ttmDps": 0.7,
      "trailingYield": 2.06,
      "forwardYield": null,
      "latestDividend": 0.26,
      "exDate": "Jul 16, 2026",
      "recordDate": "Jul 16, 2026",
      "payDate": "Aug 14, 2026",
      "dividendStatus": "Paid",
      "rating": "Hold / Buy dips",
      "ratingClass": "hold",
      "reason": "Strong operating growth and dividend coverage, but the current yield remains modest and a lower entry price would improve income return.",
      "buyLow": 29,
      "buyHigh": 32,
      "buyYieldLow": 2.19,
      "buyYieldHigh": 2.41,
      "zoneStatus": "above",
      "allocation": 7,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=91",
      "dividendUrl": "https://www.jamstockex.com/?tag=KW",
      "sa": "https://stockanalysis.com/quote/jmse/KW/",
      "source": "JSE",
      "ytd": 6.25,
      "volume": 685936
    },
    {
      "rank": 8,
      "ticker": "LASD",
      "company": "Lasco Distributors Limited",
      "price": 3.19,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.21,
      "dayPct": -6.18,
      "w1": -2.01,
      "m1": 3.64,
      "m3": 10.68,
      "m6": 0.59,
      "y1": -2.29,
      "performanceSource": "SA",
      "ttmDps": 0.12,
      "trailingYield": 3.76,
      "forwardYield": null,
      "latestDividend": 0.09,
      "exDate": "Aug 14, 2026",
      "recordDate": "Aug 14, 2026",
      "payDate": "Aug 28, 2026",
      "dividendStatus": "Dividend cut 25% YoY",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "The yield remains useful, but the latest annual dividend fell from J$0.12 to J$0.09 and earnings remain softer, reducing dividend-growth appeal.",
      "buyLow": 2.85,
      "buyHigh": 3.1,
      "buyYieldLow": 3.87,
      "buyYieldHigh": 4.21,
      "zoneStatus": "above",
      "allocation": 6,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=99",
      "dividendUrl": "https://www.jamstockex.com/?tag=LASD",
      "sa": "https://stockanalysis.com/quote/jmse/LASD/",
      "source": "JSE",
      "ytd": 0.59,
      "volume": 295776
    },
    {
      "rank": 9,
      "ticker": "BIL",
      "company": "Barita Investments Limited",
      "price": 64.81,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.08,
      "dayPct": -0.12,
      "w1": 1.27,
      "m1": -4.71,
      "m3": -4.71,
      "m6": -6.09,
      "y1": -7.44,
      "performanceSource": "SA",
      "ttmDps": 2.398,
      "trailingYield": 3.7,
      "forwardYield": null,
      "latestDividend": 2.398,
      "exDate": "Oct 17, 2025",
      "recordDate": "Oct 17, 2025",
      "payDate": "Oct 31, 2025",
      "dividendStatus": "No new declaration",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "The yield is useful and earnings have recovered, but valuation remains relatively demanding and a fresher dividend declaration is needed.",
      "buyLow": 60,
      "buyHigh": 65,
      "buyYieldLow": 3.69,
      "buyYieldHigh": 4,
      "zoneStatus": "in",
      "allocation": 4,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=21",
      "dividendUrl": "https://www.jamstockex.com/?tag=BIL",
      "sa": "https://stockanalysis.com/quote/jmse/BIL/",
      "source": "JSE",
      "ytd": -14.44,
      "volume": 10978
    },
    {
      "rank": 10,
      "ticker": "JMMBGL",
      "company": "JMMB Group Limited",
      "price": 14.82,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.15,
      "dayPct": 1.02,
      "w1": 3.74,
      "m1": -0.2,
      "m3": 0.39,
      "m6": -10.18,
      "y1": -21.49,
      "performanceSource": "SA",
      "ttmDps": 0.2,
      "trailingYield": 1.35,
      "forwardYield": null,
      "latestDividend": 0.35,
      "exDate": "Jul 29, 2026",
      "recordDate": "Jul 29, 2026",
      "payDate": "Sep 3, 2026",
      "dividendStatus": "Payment pending",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "Price is inside the buy zone, but earnings and dividend consistency remain materially weaker than the higher-ranked names.",
      "buyLow": 13.5,
      "buyHigh": 15,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 3,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=319",
      "dividendUrl": "https://www.jamstockex.com/?tag=JMMBGL",
      "sa": "https://stockanalysis.com/quote/jmse/JMMBGL/",
      "source": "JSE",
      "ytd": -23.46,
      "volume": 249436
    },
    {
      "rank": 11,
      "ticker": "TJH",
      "company": "TransJamaican Highway Limited",
      "price": 11.18,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.04,
      "dayPct": -0.36,
      "w1": 6.31,
      "m1": 21.29,
      "m3": 52.64,
      "m6": 68.61,
      "y1": 204.86,
      "performanceSource": "SA",
      "ttmDps": 0.294,
      "trailingYield": 2.63,
      "forwardYield": null,
      "latestDividend": 0.16503,
      "exDate": "Apr 7, 2026",
      "recordDate": "Apr 7, 2026",
      "payDate": "Apr 28, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Hold / Wait",
      "ratingClass": "hold",
      "reason": "Excellent operating and capital-appreciation momentum, but the 22.28% one-month and 204.05% one-year rise has compressed the dividend yield for new buyers.",
      "buyLow": 8.5,
      "buyHigh": 9.75,
      "buyYieldLow": 3.02,
      "buyYieldHigh": 3.46,
      "zoneStatus": "above",
      "allocation": 2,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600100",
      "dividendUrl": "https://www.jamstockex.com/?tag=TJH",
      "sa": "https://stockanalysis.com/quote/jmse/TJH/",
      "source": "JSE",
      "ytd": 130.67,
      "volume": 3021617
    },
    {
      "rank": 12,
      "ticker": "SVL",
      "company": "Supreme Ventures Limited",
      "price": 17.85,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.21,
      "dayPct": 1.19,
      "w1": -0.85,
      "m1": -5.16,
      "m3": 1.16,
      "m6": -1.02,
      "y1": -7.43,
      "performanceSource": "SA",
      "ttmDps": 0.56,
      "trailingYield": 3.14,
      "forwardYield": null,
      "latestDividend": 0.2635,
      "exDate": "Aug 17, 2026",
      "recordDate": "Aug 17, 2026",
      "payDate": "Sep 30, 2026",
      "dividendStatus": "Ex-dividend passed",
      "rating": "Hold",
      "ratingClass": "hold",
      "reason": "Income is acceptable and earnings have improved, but payout sustainability remains less comfortable than the higher-ranked dividend names.",
      "buyLow": 15,
      "buyHigh": 16.5,
      "buyYieldLow": 3.39,
      "buyYieldHigh": 3.73,
      "zoneStatus": "above",
      "allocation": 1,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=139",
      "dividendUrl": "https://www.jamstockex.com/?tag=SVL",
      "sa": "https://stockanalysis.com/quote/jmse/SVL/",
      "source": "JSE",
      "ytd": -10.79,
      "volume": 14724
    }
  ]
};
