window.JSE_DASHBOARD_DATA = {
  "updated": "August 20, 2026",
  "priceLabel": "JSE official close where available / StockAnalysis delayed fallback",
  "stocks": [
    {
      "rank": 1,
      "ticker": "SEP",
      "company": "Seprod",
      "price": 74.82,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.55,
      "dayPct": 2.12,
      "w1": 0.27,
      "m1": 3.01,
      "m3": -8.29,
      "m6": -7.42,
      "y1": -2.64,
      "performanceSource": "SA",
      "ttmDps": 1.82,
      "trailingYield": 2.43,
      "forwardYield": null,
      "latestDividend": 0.605,
      "exDate": "May 15, 2026",
      "recordDate": "May 15, 2026",
      "payDate": "Jun 5, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Low payout and strong earnings capacity support selective buying, but the price is at the upper edge of the accumulation range.",
      "buyLow": 68,
      "buyHigh": 75,
      "buyYieldLow": 2.43,
      "buyYieldHigh": 2.68,
      "zoneStatus": "in",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=137",
      "dividendUrl": "https://www.jamstockex.com/?tag=SEP",
      "sa": "https://stockanalysis.com/quote/jmse/SEP/",
      "source": "JSE",
      "ytd": -10.7,
      "volume": 106829,
      "sector": "Manufacturing / Distribution",
      "score": 87
    },
    {
      "rank": 2,
      "ticker": "KW",
      "company": "Kingston Wharves",
      "price": 33.94,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.06,
      "dayPct": -0.18,
      "w1": -2.11,
      "m1": -6.41,
      "m3": -10.84,
      "m6": -2.86,
      "y1": 9.5,
      "performanceSource": "SA",
      "ttmDps": 0.7,
      "trailingYield": 2.06,
      "forwardYield": null,
      "latestDividend": 0.26,
      "exDate": "Jul 16, 2026",
      "recordDate": "Jul 16, 2026",
      "payDate": "Aug 14, 2026",
      "dividendStatus": "Paid",
      "rating": "Hold / Buy dips",
      "ratingClass": "hold",
      "reason": "Strong operating growth and dividend coverage, but the current yield remains modest and a lower entry price would improve income return.",
      "buyLow": 29,
      "buyHigh": 32,
      "buyYieldLow": 2.19,
      "buyYieldHigh": 2.41,
      "zoneStatus": "above",
      "allocation": 7,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=91",
      "dividendUrl": "https://www.jamstockex.com/?tag=KW",
      "sa": "https://stockanalysis.com/quote/jmse/KW/",
      "source": "JSE",
      "ytd": 6.25,
      "volume": 685936,
      "sector": "Infrastructure / Transportation",
      "score": 84
    },
    {
      "rank": 3,
      "ticker": "NCBFG",
      "company": "NCB Financial Group",
      "price": 71.29,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.78,
      "dayPct": 1.11,
      "w1": -4.59,
      "m1": -4.46,
      "m3": 34.07,
      "m6": 63.22,
      "y1": 73.17,
      "performanceSource": "SA",
      "ttmDps": 2,
      "trailingYield": 2.81,
      "forwardYield": null,
      "latestDividend": 0.5,
      "exDate": "Aug 28, 2026",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 11, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "The pullback improves entry value while the current dividend remains comfortably covered relative to the recovery in profitability.",
      "buyLow": 64,
      "buyHigh": 70,
      "buyYieldLow": 2.86,
      "buyYieldHigh": 3.13,
      "zoneStatus": "above",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600012",
      "dividendUrl": "https://www.jamstockex.com/?tag=NCBFG",
      "sa": "https://stockanalysis.com/quote/jmse/NCBFG/",
      "source": "JSE",
      "ytd": 97.22,
      "volume": 51695,
      "sector": "Banks & Financial Services",
      "score": 80
    },
    {
      "rank": 4,
      "ticker": "SJ",
      "company": "Sagicor Group Jamaica",
      "price": 41.06,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.11,
      "dayPct": 0.27,
      "w1": -0.24,
      "m1": 5.67,
      "m3": -1.61,
      "m6": 0.25,
      "y1": -2.2,
      "performanceSource": "SA",
      "ttmDps": 1.78,
      "trailingYield": 4.34,
      "forwardYield": null,
      "latestDividend": 0.89,
      "exDate": "Apr 14, 2026",
      "recordDate": "Apr 14, 2026",
      "payDate": "May 6, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Strong dividend history and attractive actual trailing income support accumulation near the buy-zone ceiling, though recent earnings softness warrants monitoring.",
      "buyLow": 36,
      "buyHigh": 41,
      "buyYieldLow": 4.34,
      "buyYieldHigh": 4.94,
      "zoneStatus": "above",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=297",
      "dividendUrl": "https://www.jamstockex.com/?tag=SJ",
      "sa": "https://stockanalysis.com/quote/jmse/SJ/",
      "source": "JSE",
      "ytd": -3.33,
      "volume": 28579,
      "sector": "Financial Services / Insurance",
      "score": 80
    },
    {
      "rank": 5,
      "ticker": "SGJ",
      "company": "Scotia Group Jamaica",
      "sector": "Banks & Financial Services",
      "price": 57.01,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.02,
      "dayPct": -0.04,
      "w1": -0.47,
      "m1": -0.21,
      "ytd": null,
      "m3": 3.69,
      "m6": null,
      "y1": null,
      "ttmDps": 1.8,
      "trailingYield": 3.16,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Quality / Defensive • score 76. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 50,
      "buyHigh": 57,
      "buyYieldLow": 3.16,
      "buyYieldHigh": 3.6,
      "zoneStatus": "above",
      "allocation": 76,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=133",
      "dividendUrl": "https://www.jamstockex.com/?tag=SGJ",
      "sa": "https://stockanalysis.com/quote/jmse/SGJ/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 76,
      "volume": 44206
    },
    {
      "rank": 6,
      "ticker": "TJH",
      "company": "TransJamaican Highway",
      "price": 11.18,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.04,
      "dayPct": -0.36,
      "w1": 6.33,
      "m1": 20.97,
      "m3": 52.23,
      "m6": 68.61,
      "y1": 204.86,
      "performanceSource": "SA",
      "ttmDps": 0.294,
      "trailingYield": 2.63,
      "forwardYield": null,
      "latestDividend": 0.16503,
      "exDate": "Apr 7, 2026",
      "recordDate": "Apr 7, 2026",
      "payDate": "Apr 28, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Hold / Wait",
      "ratingClass": "hold",
      "reason": "Excellent operating and capital-appreciation momentum, but the 22.28% one-month and 204.05% one-year rise has compressed the dividend yield for new buyers.",
      "buyLow": 8.5,
      "buyHigh": 9.75,
      "buyYieldLow": 3.02,
      "buyYieldHigh": 3.46,
      "zoneStatus": "above",
      "allocation": 2,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600100",
      "dividendUrl": "https://www.jamstockex.com/?tag=TJH",
      "sa": "https://stockanalysis.com/quote/jmse/TJH/",
      "source": "JSE",
      "ytd": 130.67,
      "volume": 3021617,
      "sector": "Infrastructure / Transportation",
      "score": 73
    },
    {
      "rank": 7,
      "ticker": "CPJ",
      "company": "Caribbean Producers Jamaica",
      "sector": "Consumer / Distribution",
      "price": 5.24,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.09,
      "dayPct": 1.75,
      "w1": 3.96,
      "m1": -3.31,
      "ytd": null,
      "m3": -4.55,
      "m6": null,
      "y1": null,
      "ttmDps": 0,
      "trailingYield": 0,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Deep Value / Earnings Quality Watch • score 72. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 5,
      "buyHigh": 6,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 72,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=256",
      "dividendUrl": "https://www.jamstockex.com/?tag=CPJ",
      "sa": "https://stockanalysis.com/quote/jmse/CPJ/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 72,
      "volume": 305847
    },
    {
      "rank": 8,
      "ticker": "GK",
      "company": "GraceKennedy",
      "price": 76.29,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.24,
      "dayPct": 1.65,
      "w1": -2.03,
      "m1": 4.78,
      "m3": 3.64,
      "m6": 5.1,
      "y1": 8.09,
      "performanceSource": "SA",
      "ttmDps": 2.37,
      "trailingYield": 3.11,
      "forwardYield": null,
      "latestDividend": 0.7,
      "exDate": "Upcoming",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 21, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Strong Buy",
      "ratingClass": "buy",
      "reason": "Best overall mix of business quality, sensible valuation and dividend coverage.",
      "buyLow": 70,
      "buyHigh": 76,
      "buyYieldLow": 3.12,
      "buyYieldHigh": 3.39,
      "zoneStatus": "above",
      "allocation": 16,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=55",
      "dividendUrl": "https://www.jamstockex.com/?tag=GK",
      "sa": "https://stockanalysis.com/quote/jmse/GK/",
      "source": "JSE",
      "ytd": 4.03,
      "volume": 477221,
      "sector": "Conglomerates",
      "score": 72
    },
    {
      "rank": 9,
      "ticker": "GENAC",
      "company": "General Accident Insurance",
      "sector": "Insurance",
      "price": 8.89,
      "priceDate": "2026-08-19 • JSE",
      "dayJmd": -0.04,
      "dayPct": -0.45,
      "w1": 2.98,
      "m1": -4.84,
      "ytd": null,
      "m3": 16.89,
      "m6": null,
      "y1": null,
      "ttmDps": 0.08,
      "trailingYield": 0.9,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Growth / Valuation Watch • score 71. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 7.5,
      "buyHigh": 9,
      "buyYieldLow": 0.89,
      "buyYieldHigh": 1.07,
      "zoneStatus": "in",
      "allocation": 71,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=258",
      "dividendUrl": "https://www.jamstockex.com/?tag=GENAC",
      "sa": "https://stockanalysis.com/quote/jmse/GENAC/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 71
    },
    {
      "rank": 10,
      "ticker": "CAR",
      "company": "Carreras",
      "price": 34.94,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.55,
      "dayPct": 4.64,
      "w1": 0.26,
      "m1": 10.36,
      "m3": 51.85,
      "m6": 63.37,
      "y1": 91.86,
      "performanceSource": "SA",
      "ttmDps": 1.35,
      "trailingYield": 3.86,
      "forwardYield": null,
      "latestDividend": 0.41,
      "exDate": "Aug 28, 2026",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 17, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Strong current income, but a high payout and sharp recent rerating argue against chasing above the dividend buy zone.",
      "buyLow": 29,
      "buyHigh": 32,
      "buyYieldLow": 4.22,
      "buyYieldHigh": 4.66,
      "zoneStatus": "above",
      "allocation": 11,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=39",
      "dividendUrl": "https://www.jamstockex.com/?tag=CAR",
      "sa": "https://stockanalysis.com/quote/jmse/CAR/",
      "source": "JSE",
      "ytd": 83.33,
      "volume": 148878,
      "sector": "Consumer Staples",
      "score": 70
    },
    {
      "rank": 11,
      "ticker": "SALF",
      "company": "Salada Foods Jamaica",
      "sector": "Consumer Staples",
      "price": 2.6,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.05,
      "dayPct": -1.89,
      "w1": 3.92,
      "m1": 1.53,
      "ytd": null,
      "m3": -7.02,
      "m6": null,
      "y1": null,
      "ttmDps": 0.13,
      "trailingYield": 5,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Quality Balance Sheet / Slow EPS • score 68. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 2.4,
      "buyHigh": 2.5,
      "buyYieldLow": 5.2,
      "buyYieldHigh": 5.42,
      "zoneStatus": "above",
      "allocation": 68,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=131",
      "dividendUrl": "https://www.jamstockex.com/?tag=SALF",
      "sa": "https://stockanalysis.com/quote/jmse/SALF/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 68,
      "volume": 21240
    },
    {
      "rank": 12,
      "ticker": "MASSY",
      "company": "Massy Holdings",
      "sector": "Conglomerates",
      "price": 72.5,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.05,
      "dayPct": 0.07,
      "w1": 0,
      "m1": 0,
      "ytd": null,
      "m3": 0,
      "m6": null,
      "y1": null,
      "ttmDps": 4.14,
      "trailingYield": 5.71,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Income / Below Book • score 68. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 65,
      "buyHigh": 72,
      "buyYieldLow": 5.75,
      "buyYieldHigh": 6.37,
      "zoneStatus": "above",
      "allocation": 68,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600126",
      "dividendUrl": "https://www.jamstockex.com/?tag=MASSY",
      "sa": "https://stockanalysis.com/quote/jmse/MASSY/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 68,
      "volume": 38
    },
    {
      "rank": 13,
      "ticker": "BIL",
      "company": "Barita Investments",
      "price": 64.81,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.08,
      "dayPct": -0.12,
      "w1": -0.31,
      "m1": -4.72,
      "m3": -4.72,
      "m6": -6.09,
      "y1": -7.44,
      "performanceSource": "SA",
      "ttmDps": 2.398,
      "trailingYield": 3.7,
      "forwardYield": null,
      "latestDividend": 2.398,
      "exDate": "Oct 17, 2025",
      "recordDate": "Oct 17, 2025",
      "payDate": "Oct 31, 2025",
      "dividendStatus": "No new declaration",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "The yield is useful and earnings have recovered, but valuation remains relatively demanding and a fresher dividend declaration is needed.",
      "buyLow": 60,
      "buyHigh": 65,
      "buyYieldLow": 3.69,
      "buyYieldHigh": 4,
      "zoneStatus": "in",
      "allocation": 4,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=21",
      "dividendUrl": "https://www.jamstockex.com/?tag=BIL",
      "sa": "https://stockanalysis.com/quote/jmse/BIL/",
      "source": "JSE",
      "ytd": -14.44,
      "volume": 10978,
      "sector": "Investments / Securities",
      "score": 59
    },
    {
      "rank": 14,
      "ticker": "JMMBGL",
      "company": "JMMB Group",
      "price": 14.82,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.15,
      "dayPct": 1.02,
      "w1": 0.73,
      "m1": -1.31,
      "m3": -0.72,
      "m6": -10.18,
      "y1": -21.49,
      "performanceSource": "SA",
      "ttmDps": 0.2,
      "trailingYield": 1.35,
      "forwardYield": null,
      "latestDividend": 0.35,
      "exDate": "Jul 29, 2026",
      "recordDate": "Jul 29, 2026",
      "payDate": "Sep 3, 2026",
      "dividendStatus": "Payment pending",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "Price is inside the buy zone, but earnings and dividend consistency remain materially weaker than the higher-ranked names.",
      "buyLow": 13.5,
      "buyHigh": 15,
      "buyYieldLow": 1.33,
      "buyYieldHigh": 1.54,
      "zoneStatus": "in",
      "allocation": 3,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=319",
      "dividendUrl": "https://www.jamstockex.com/?tag=JMMBGL",
      "sa": "https://stockanalysis.com/quote/jmse/JMMBGL/",
      "source": "JSE",
      "ytd": -23.46,
      "volume": 249436,
      "sector": "Banks & Financial Services",
      "score": 57
    },
    {
      "rank": 15,
      "ticker": "SCIJMD",
      "company": "Sygnus Credit Investments",
      "sector": "Investments / Securities",
      "price": 9.48,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.06,
      "dayPct": 0.64,
      "w1": 1.62,
      "m1": -3.89,
      "ytd": null,
      "m3": -7.02,
      "m6": null,
      "y1": null,
      "ttmDps": 0.71,
      "trailingYield": 7.49,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Deep P/B Discount / Very Weak ROE • score 50. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 8,
      "buyHigh": 9,
      "buyYieldLow": 7.89,
      "buyYieldHigh": 8.88,
      "zoneStatus": "above",
      "allocation": 50,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600069",
      "dividendUrl": "https://www.jamstockex.com/?tag=SCIJMD",
      "sa": "https://stockanalysis.com/quote/jmse/SCIJMD/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 50,
      "volume": 50531
    },
    {
      "rank": 16,
      "ticker": "JBG",
      "company": "Jamaica Broilers Group",
      "sector": "Consumer Staples / Manufacturing",
      "price": 12.48,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.71,
      "dayPct": 6.03,
      "w1": -2.65,
      "m1": -7.15,
      "ytd": null,
      "m3": -17.1,
      "m6": null,
      "y1": null,
      "ttmDps": 0,
      "trailingYield": 0,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Below Book / Loss-Making • score 36. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 36,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=65",
      "dividendUrl": "https://www.jamstockex.com/?tag=JBG",
      "sa": "https://stockanalysis.com/quote/jmse/JBG/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 36,
      "volume": 86462
    },
    {
      "rank": 17,
      "ticker": "WIG",
      "company": "Wigton Energy",
      "sector": "Energy",
      "price": 1.03,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": null,
      "dayPct": null,
      "w1": -1.9,
      "m1": -7.21,
      "ytd": null,
      "m3": -12.71,
      "m6": null,
      "y1": null,
      "ttmDps": 0.003,
      "trailingYield": 0.29,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "High P/B / Weak ROE • score 26. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 26,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600087",
      "dividendUrl": "https://www.jamstockex.com/?tag=WIG",
      "sa": "https://stockanalysis.com/quote/jmse/WIG/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 26,
      "volume": 2956325
    },
    {
      "rank": 18,
      "ticker": "138SL",
      "company": "138 Student Living Jamaica",
      "sector": "Real Estate",
      "price": 2.86,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.05,
      "dayPct": 1.78,
      "w1": -6.02,
      "m1": 21.12,
      "ytd": null,
      "m3": -11.91,
      "m6": null,
      "y1": null,
      "ttmDps": 0,
      "trailingYield": 0,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Deep Value / Balance-Sheet & Liquidity Risk • score 61. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 2.5,
      "buyHigh": 3,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 61,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=311",
      "dividendUrl": "https://www.jamstockex.com/?tag=138SL",
      "sa": "https://stockanalysis.com/quote/jmse/138SL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 61,
      "volume": 730
    },
    {
      "rank": 19,
      "ticker": "ASBH",
      "company": "A.S. Bryden & Sons Holdings",
      "sector": "Manufacturing / Distribution",
      "price": 24.98,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": null,
      "dayPct": null,
      "w1": 1.75,
      "m1": 5.89,
      "ytd": null,
      "m3": -10.79,
      "m6": null,
      "y1": null,
      "ttmDps": 0.62,
      "trailingYield": 2.48,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Growth Platform / Valuation & Leverage Risk • score 43. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 12,
      "buyHigh": 15,
      "buyYieldLow": 4.13,
      "buyYieldHigh": 5.17,
      "zoneStatus": "above",
      "allocation": 43,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600148",
      "dividendUrl": "https://www.jamstockex.com/?tag=ASBH",
      "sa": "https://stockanalysis.com/quote/jmse/ASBH/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 43,
      "volume": 15
    },
    {
      "rank": 20,
      "ticker": "BRG",
      "company": "Berger Paints Jamaica",
      "sector": "Manufacturing",
      "price": 5.49,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.92,
      "dayPct": -14.35,
      "w1": 23.08,
      "m1": 28,
      "ytd": null,
      "m3": 25.74,
      "m6": null,
      "y1": null,
      "ttmDps": 0.13,
      "trailingYield": 2.37,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Weak ROE / Rich Earnings Multiple • score 37. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 3.2,
      "buyHigh": 3.8,
      "buyYieldLow": 3.42,
      "buyYieldHigh": 4.06,
      "zoneStatus": "above",
      "allocation": 37,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=23",
      "dividendUrl": "https://www.jamstockex.com/?tag=BRG",
      "sa": "https://stockanalysis.com/quote/jmse/BRG/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 37,
      "volume": 5612
    },
    {
      "rank": 21,
      "ticker": "CCC",
      "company": "Caribbean Cement Company",
      "sector": "Construction & Materials",
      "price": 107.84,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.63,
      "dayPct": 0.59,
      "w1": 3.83,
      "m1": 1.37,
      "ytd": null,
      "m3": 4.34,
      "m6": null,
      "y1": null,
      "ttmDps": 2.1,
      "trailingYield": 1.95,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Quality + Cash Flow + Strong ROE • score 84. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 100,
      "buyHigh": 115,
      "buyYieldLow": 1.83,
      "buyYieldHigh": 2.1,
      "zoneStatus": "in",
      "allocation": 84,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=37",
      "dividendUrl": "https://www.jamstockex.com/?tag=CCC",
      "sa": "https://stockanalysis.com/quote/jmse/CCC/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 84,
      "volume": 22154
    },
    {
      "rank": 22,
      "ticker": "CPFV",
      "company": "Eppley Caribbean Property Fund SCC",
      "sector": "Real Estate",
      "price": 44.06,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.33,
      "dayPct": 0.75,
      "w1": -0.59,
      "m1": -1.73,
      "ytd": null,
      "m3": -4.93,
      "m6": null,
      "y1": null,
      "ttmDps": 1.58,
      "trailingYield": 3.59,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Income Fund / NAV Data Required • score 56. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 56,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600091",
      "dividendUrl": "https://www.jamstockex.com/?tag=CPFV",
      "sa": "https://stockanalysis.com/quote/jmse/CPFV/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 56,
      "volume": 506
    },
    {
      "rank": 23,
      "ticker": "EPLY",
      "company": "Eppley",
      "sector": "Investments / Securities",
      "price": 33.32,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.64,
      "dayPct": 1.96,
      "w1": -0.21,
      "m1": -0.7,
      "ytd": null,
      "m3": -9.22,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Profitable / Leverage & Book-Premium Watch • score 70. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 28,
      "buyHigh": 32,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 70,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=279",
      "dividendUrl": "https://www.jamstockex.com/?tag=EPLY",
      "sa": "https://stockanalysis.com/quote/jmse/EPLY/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 70,
      "volume": 76910
    },
    {
      "rank": 24,
      "ticker": "FIRSTROCKJMD",
      "company": "First Rock Real Estate Investments",
      "sector": "Real Estate",
      "price": 5.72,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -1.31,
      "dayPct": -18.63,
      "w1": 24.56,
      "m1": -11.39,
      "ytd": null,
      "m3": -29.79,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Deep Book Discount / Negative Returns • score 33. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 33,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600097",
      "dividendUrl": "https://www.jamstockex.com/?tag=FIRSTROCKJMD",
      "sa": "https://stockanalysis.com/quote/jmse/FIRSTROCKJMD/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 33,
      "volume": 8009
    },
    {
      "rank": 25,
      "ticker": "GHL",
      "company": "Guardian Holdings",
      "sector": "Insurance",
      "price": 365,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 4.68,
      "dayPct": 1.3,
      "w1": 0,
      "m1": 4.29,
      "ytd": null,
      "m3": 5.19,
      "m6": null,
      "y1": null,
      "ttmDps": 23.27,
      "trailingYield": 6.38,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Low Earnings Multiple + Income / Earnings Decline • score 76. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 320,
      "buyHigh": 370,
      "buyYieldLow": 6.29,
      "buyYieldHigh": 7.27,
      "zoneStatus": "in",
      "allocation": 76,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=57",
      "dividendUrl": "https://www.jamstockex.com/?tag=GHL",
      "sa": "https://stockanalysis.com/quote/jmse/GHL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 76,
      "volume": 407
    },
    {
      "rank": 26,
      "ticker": "ENERGY",
      "company": "Innovative Energy Group",
      "sector": "Energy",
      "price": 1.04,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.11,
      "dayPct": 11.83,
      "w1": 4,
      "m1": 4,
      "ytd": null,
      "m3": 4,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Weak Returns / Expensive Earnings • score 31. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 0.65,
      "buyHigh": 0.75,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 31,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=41",
      "dividendUrl": "https://www.jamstockex.com/?tag=ENERGY",
      "sa": "https://stockanalysis.com/quote/jmse/ENERGY/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 31,
      "volume": 34203
    },
    {
      "rank": 27,
      "ticker": "JP",
      "company": "Jamaica Producers Group",
      "sector": "Conglomerates",
      "price": 21.5,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.02,
      "dayPct": -0.09,
      "w1": -0.44,
      "m1": -7.64,
      "ytd": null,
      "m3": -15.33,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Asset Value / Low ROE & Earnings-Quality Watch • score 59. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 18,
      "buyHigh": 21,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 59,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=75",
      "dividendUrl": "https://www.jamstockex.com/?tag=JP",
      "sa": "https://stockanalysis.com/quote/jmse/JP/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 59,
      "volume": 2109
    },
    {
      "rank": 28,
      "ticker": "KPREIT",
      "company": "Kingston Properties",
      "sector": "Real Estate",
      "price": 11.84,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 1.15,
      "dayPct": 10.76,
      "w1": -2.73,
      "m1": 2,
      "ytd": null,
      "m3": -11.43,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Near-Book Property Value / Moderate ROE • score 65. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 9,
      "buyHigh": 10.5,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 65,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=89",
      "dividendUrl": "https://www.jamstockex.com/?tag=KPREIT",
      "sa": "https://stockanalysis.com/quote/jmse/KPREIT/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 65,
      "volume": 4243
    },
    {
      "rank": 29,
      "ticker": "LASD",
      "company": "Lasco Distributors",
      "price": 3.19,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.21,
      "dayPct": -6.18,
      "w1": -13.17,
      "m1": -6.06,
      "m3": 0.32,
      "m6": 0.59,
      "y1": -2.29,
      "performanceSource": "SA",
      "ttmDps": 0.12,
      "trailingYield": 3.76,
      "forwardYield": null,
      "latestDividend": 0.09,
      "exDate": "Aug 14, 2026",
      "recordDate": "Aug 14, 2026",
      "payDate": "Aug 28, 2026",
      "dividendStatus": "Dividend cut 25% YoY",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "The yield remains useful, but the latest annual dividend fell from J$0.12 to J$0.09 and earnings remain softer, reducing dividend-growth appeal.",
      "buyLow": 2.85,
      "buyHigh": 3.1,
      "buyYieldLow": 3.87,
      "buyYieldHigh": 4.21,
      "zoneStatus": "above",
      "allocation": 6,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=99",
      "dividendUrl": "https://www.jamstockex.com/?tag=LASD",
      "sa": "https://stockanalysis.com/quote/jmse/LASD/",
      "source": "JSE",
      "ytd": 0.59,
      "volume": 295776,
      "sector": "Consumer / Distribution",
      "score": 76
    },
    {
      "rank": 30,
      "ticker": "LASM",
      "company": "Lasco Manufacturing",
      "price": 8.15,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.04,
      "dayPct": -0.49,
      "w1": 2.5,
      "m1": 24.24,
      "m3": 20.59,
      "m6": 29.29,
      "y1": 36.61,
      "performanceSource": "SA",
      "ttmDps": 0.19,
      "trailingYield": 2.33,
      "forwardYield": null,
      "latestDividend": 0.2,
      "exDate": "Aug 14, 2026",
      "recordDate": "Aug 14, 2026",
      "payDate": "Aug 28, 2026",
      "dividendStatus": "Dividend increased 5.3% YoY",
      "rating": "Hold / Buy dips",
      "ratingClass": "hold",
      "reason": "The dividend increased and coverage is strong, but a 23% one-month rally leaves the share price materially above the preferred income entry zone.",
      "buyLow": 6.25,
      "buyHigh": 7,
      "buyYieldLow": 2.71,
      "buyYieldHigh": 3.04,
      "zoneStatus": "above",
      "allocation": 8,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=103",
      "dividendUrl": "https://www.jamstockex.com/?tag=LASM",
      "sa": "https://stockanalysis.com/quote/jmse/LASM/",
      "source": "JSE",
      "ytd": 42.04,
      "volume": 600640,
      "sector": "Manufacturing",
      "score": 80
    },
    {
      "rank": 31,
      "ticker": "MTL",
      "company": "Margaritaville (Turks)",
      "sector": "Tourism / Hospitality",
      "price": 0.0501,
      "priceDate": "2026-08-12 • SA",
      "dayJmd": null,
      "dayPct": null,
      "w1": -33.42,
      "m1": -14.47,
      "ytd": null,
      "m3": -29.42,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Deep Value / Currency & Liquidity Risk • score 60. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 60,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600081",
      "dividendUrl": "https://www.jamstockex.com/?tag=MTL",
      "sa": "https://stockanalysis.com/quote/jmse/MTL/",
      "source": "SA",
      "performanceSource": "SA",
      "score": 60
    },
    {
      "rank": 32,
      "ticker": "MGL",
      "company": "Mayberry Group",
      "sector": "Investments / Securities",
      "price": 5.69,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.26,
      "dayPct": -4.37,
      "w1": 3.48,
      "m1": -0.5,
      "ytd": null,
      "m3": -2.46,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Loss-Making / Negative ROE • score 22. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 22,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600150",
      "dividendUrl": "https://www.jamstockex.com/?tag=MGL",
      "sa": "https://stockanalysis.com/quote/jmse/MGL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 22,
      "volume": 616
    },
    {
      "rank": 33,
      "ticker": "MJE",
      "company": "Mayberry Jamaican Equities",
      "sector": "Investments / Securities",
      "price": 6.51,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.17,
      "dayPct": -2.54,
      "w1": 2.27,
      "m1": 12.5,
      "ytd": null,
      "m3": 3.53,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Loss-Making / Negative ROE • score 24. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 24,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600072",
      "dividendUrl": "https://www.jamstockex.com/?tag=MJE",
      "sa": "https://stockanalysis.com/quote/jmse/MJE/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 24,
      "volume": 20285
    },
    {
      "rank": 34,
      "ticker": "MPCCEL",
      "company": "MPC Caribbean Clean Energy",
      "sector": "Energy",
      "price": 24.95,
      "priceDate": "2026-08-19 • JSE",
      "dayJmd": -0.05,
      "dayPct": -0.2,
      "w1": -13.79,
      "m1": -16.39,
      "ytd": null,
      "m3": -20.18,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Deep Book Discount / Negative Returns • score 25. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 25,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600078",
      "dividendUrl": "https://www.jamstockex.com/?tag=MPCCEL",
      "sa": "https://stockanalysis.com/quote/jmse/MPCCEL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 25
    },
    {
      "rank": 35,
      "ticker": "PAL",
      "company": "Palace Amusement",
      "sector": "Tourism / Entertainment",
      "price": 0.5,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.03,
      "dayPct": 6.38,
      "w1": -18.03,
      "m1": 51.52,
      "ytd": null,
      "m3": -26.47,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Loss-Making / Weak Liquidity • score 20. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 20,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=113",
      "dividendUrl": "https://www.jamstockex.com/?tag=PAL",
      "sa": "https://stockanalysis.com/quote/jmse/PAL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 20,
      "volume": 23352
    },
    {
      "rank": 36,
      "ticker": "PJAM",
      "company": "Pan Jamaica Group",
      "sector": "Conglomerates",
      "price": 43.79,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -1.6,
      "dayPct": -3.53,
      "w1": 1.66,
      "m1": -2.22,
      "ytd": null,
      "m3": -3.34,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Below Book + FCF / Low ROE • score 70. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 40,
      "buyHigh": 46,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 70,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=121",
      "dividendUrl": "https://www.jamstockex.com/?tag=PJAM",
      "sa": "https://stockanalysis.com/quote/jmse/PJAM/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 70,
      "volume": 1866
    },
    {
      "rank": 37,
      "ticker": "PJX",
      "company": "Portland JSX",
      "sector": "Investments / Securities",
      "price": 6.65,
      "priceDate": "Weekly master universe",
      "dayJmd": null,
      "dayPct": null,
      "w1": 0,
      "m1": 15.05,
      "ytd": null,
      "m3": -16.87,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Deep Losses / Negative ROE • score 15. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 15,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=337",
      "dividendUrl": "https://www.jamstockex.com/?tag=PJX",
      "sa": "https://stockanalysis.com/quote/jmse/PJX/",
      "source": "SA",
      "performanceSource": "SA",
      "score": 15
    },
    {
      "rank": 38,
      "ticker": "PROVEN",
      "company": "PROVEN Group",
      "sector": "Investments / Securities",
      "price": 9.39,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.13,
      "dayPct": -1.37,
      "w1": -3.34,
      "m1": -8.96,
      "ytd": null,
      "m3": -16.96,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Low Book Multiple / Leverage & Currency Complexity • score 38. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 38,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=321",
      "dividendUrl": "https://www.jamstockex.com/?tag=PROVEN",
      "sa": "https://stockanalysis.com/quote/jmse/PROVEN/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 38,
      "volume": 8320
    },
    {
      "rank": 39,
      "ticker": "PULS",
      "company": "Pulse Investments",
      "sector": "Other / Investments",
      "price": 0.81,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.06,
      "dayPct": 8,
      "w1": -3.57,
      "m1": -3.57,
      "ytd": null,
      "m3": -10,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Low ROE / Earnings Multiple Too High • score 30. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 0.5,
      "buyHigh": 0.6,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 30,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=125",
      "dividendUrl": "https://www.jamstockex.com/?tag=PULS",
      "sa": "https://stockanalysis.com/quote/jmse/PULS/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 30,
      "volume": 79
    },
    {
      "rank": 40,
      "ticker": "QWI",
      "company": "QWI Investments",
      "sector": "Investments / Securities",
      "price": 0.69,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.08,
      "dayPct": -10.39,
      "w1": 13.43,
      "m1": 5.56,
      "ytd": null,
      "m3": 5.56,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "NAV Value + Low Leverage • score 75. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 0.6,
      "buyHigh": 0.72,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 75,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600092",
      "dividendUrl": "https://www.jamstockex.com/?tag=QWI",
      "sa": "https://stockanalysis.com/quote/jmse/QWI/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 75,
      "volume": 85434
    },
    {
      "rank": 41,
      "ticker": "RJR",
      "company": "Radio Jamaica",
      "sector": "Communications / Media",
      "price": 1.08,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.12,
      "dayPct": -10,
      "w1": 2.56,
      "m1": 3.45,
      "ytd": null,
      "m3": 13.21,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Negative ROE / Loss-Making • score 15. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 15,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=127",
      "dividendUrl": "https://www.jamstockex.com/?tag=RJR",
      "sa": "https://stockanalysis.com/quote/jmse/RJR/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 15,
      "volume": 29799
    },
    {
      "rank": 42,
      "ticker": "XFUND",
      "company": "Sagicor Real Estate X Fund",
      "sector": "Real Estate",
      "price": 8.47,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.08,
      "dayPct": -0.94,
      "w1": -8.47,
      "m1": -8.36,
      "ytd": null,
      "m3": -19.19,
      "m6": null,
      "y1": null,
      "ttmDps": 0.1,
      "trailingYield": 1.18,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Property Fund / Low Yield & Sparse Current Data • score 55. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 55,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=290",
      "dividendUrl": "https://www.jamstockex.com/?tag=XFUND",
      "sa": "https://stockanalysis.com/quote/jmse/XFUND/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 55,
      "volume": 845
    },
    {
      "rank": 43,
      "ticker": "SELECTF",
      "company": "Sagicor Select Funds - Financial",
      "sector": "Investments / Funds",
      "price": 0.45,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": null,
      "dayPct": null,
      "w1": -4.26,
      "m1": 2.27,
      "ytd": null,
      "m3": 9.76,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Fund Discount / Weak ROE • score 50. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 50,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600090",
      "dividendUrl": "https://www.jamstockex.com/?tag=SELECTF",
      "sa": "https://stockanalysis.com/quote/jmse/SELECTF/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 50,
      "volume": 970275
    },
    {
      "rank": 44,
      "ticker": "SELECTMD",
      "company": "Sagicor Select Funds - Manufacturing & Distribution",
      "sector": "Investments / Funds",
      "price": 0.93,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.01,
      "dayPct": -1.06,
      "w1": -4.08,
      "m1": -1.05,
      "ytd": null,
      "m3": -1.05,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Fund Discount / Low ROE • score 52. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 52,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600096",
      "dividendUrl": "https://www.jamstockex.com/?tag=SELECTMD",
      "sa": "https://stockanalysis.com/quote/jmse/SELECTMD/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 52,
      "volume": 393867
    },
    {
      "rank": 45,
      "ticker": "TROPICAL",
      "company": "Tropical Battery Company",
      "sector": "Manufacturing / Distribution",
      "price": 1.51,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.09,
      "dayPct": 6.34,
      "w1": 9.23,
      "m1": -0.7,
      "ytd": null,
      "m3": 0,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Data-Quality Risk / Valuation Needs Verification • score 40. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 40,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600104",
      "dividendUrl": "https://www.jamstockex.com/?tag=TROPICAL",
      "sa": "https://stockanalysis.com/quote/jmse/TROPICAL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 40,
      "volume": 732860
    },
    {
      "rank": 46,
      "ticker": "VMIL",
      "company": "VM Investments",
      "sector": "Investments / Securities",
      "price": 1.53,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.07,
      "dayPct": -4.38,
      "w1": -4.76,
      "m1": 0,
      "ytd": null,
      "m3": -2.44,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Cheap P/E & P/B / High Leverage • score 58. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 1.4,
      "buyHigh": 1.6,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 58,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600034",
      "dividendUrl": "https://www.jamstockex.com/?tag=VMIL",
      "sa": "https://stockanalysis.com/quote/jmse/VMIL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 58,
      "volume": 17605
    },
    {
      "rank": 47,
      "ticker": "WIPT",
      "company": "West Indies Petroleum Terminal",
      "sector": "Energy / Infrastructure",
      "price": 9.29,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.29,
      "dayPct": 3.22,
      "w1": 2.7,
      "m1": 4.34,
      "ytd": null,
      "m3": -11.26,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "AVOID",
      "ratingClass": "avoid",
      "reason": "Extreme P/E & P/B / New-Listing Risk • score 18. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": null,
      "buyHigh": null,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 18,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600179",
      "dividendUrl": "https://www.jamstockex.com/?tag=WIPT",
      "sa": "https://stockanalysis.com/quote/jmse/WIPT/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 18,
      "volume": 320026211
    },
    {
      "rank": 48,
      "ticker": "WISYNCO",
      "company": "Wisynco Group",
      "sector": "Consumer Staples / Distribution",
      "price": 19.86,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.02,
      "dayPct": 0.1,
      "w1": 0.3,
      "m1": -0.2,
      "ytd": null,
      "m3": 1.54,
      "m6": null,
      "y1": null,
      "ttmDps": 0.46,
      "trailingYield": 2.32,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Quality + Strong Balance Sheet / Fair Value • score 74. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 17,
      "buyHigh": 19.5,
      "buyYieldLow": 2.36,
      "buyYieldHigh": 2.71,
      "zoneStatus": "above",
      "allocation": 74,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600033",
      "dividendUrl": "https://www.jamstockex.com/?tag=WISYNCO",
      "sa": "https://stockanalysis.com/quote/jmse/WISYNCO/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 74,
      "volume": 68161
    },
    {
      "rank": 49,
      "ticker": "JSE",
      "company": "Jamaica Stock Exchange",
      "sector": "Investments / Securities",
      "price": 9.15,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": -0.01,
      "dayPct": -0.11,
      "w1": 3.84,
      "m1": 2.11,
      "ytd": null,
      "m3": -19.32,
      "m6": null,
      "y1": null,
      "ttmDps": 0.5,
      "trailingYield": 5.46,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Quality Franchise / Earnings Normalization • score 65. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 8,
      "buyHigh": 9,
      "buyYieldLow": 5.56,
      "buyYieldHigh": 6.25,
      "zoneStatus": "above",
      "allocation": 65,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=276",
      "dividendUrl": "https://www.jamstockex.com/?tag=JSE",
      "sa": "https://stockanalysis.com/quote/jmse/JSE/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 65,
      "volume": 1642
    },
    {
      "rank": 50,
      "ticker": "SML",
      "company": "Stanley Motta",
      "sector": "Real Estate",
      "price": 7.34,
      "priceDate": "2026-08-19 • JSE",
      "dayJmd": -0.1,
      "dayPct": -1.34,
      "w1": 0,
      "m1": 2.05,
      "ytd": null,
      "m3": 14.79,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Asset Value + High ROE / Revaluation-Gain Risk • score 76. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 6.5,
      "buyHigh": 7.5,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 76,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600074",
      "dividendUrl": "https://www.jamstockex.com/?tag=SML",
      "sa": "https://stockanalysis.com/quote/jmse/SML/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 76
    },
    {
      "rank": 51,
      "ticker": "SIL",
      "company": "Sterling Investments",
      "sector": "Investments / Securities",
      "price": 3.27,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.25,
      "dayPct": 8.28,
      "w1": 4.13,
      "m1": 9.33,
      "ytd": null,
      "m3": 3.47,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "HOLD",
      "ratingClass": "hold",
      "reason": "Below Book / Modest ROE • score 58. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 2.6,
      "buyHigh": 3,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "above",
      "allocation": 58,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=309",
      "dividendUrl": "https://www.jamstockex.com/?tag=SIL",
      "sa": "https://stockanalysis.com/quote/jmse/SIL/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 58,
      "volume": 18069
    },
    {
      "rank": 52,
      "ticker": "SVL",
      "company": "Supreme Ventures",
      "price": 17.85,
      "priceDate": "Aug 20, 2026 • JSE",
      "dayJmd": 0.21,
      "dayPct": 1.19,
      "w1": -2.45,
      "m1": -4.89,
      "m3": 1.45,
      "m6": -1.02,
      "y1": -7.43,
      "performanceSource": "SA",
      "ttmDps": 0.56,
      "trailingYield": 3.14,
      "forwardYield": null,
      "latestDividend": 0.2635,
      "exDate": "Aug 17, 2026",
      "recordDate": "Aug 17, 2026",
      "payDate": "Sep 30, 2026",
      "dividendStatus": "Ex-dividend passed",
      "rating": "Hold",
      "ratingClass": "hold",
      "reason": "Income is acceptable and earnings have improved, but payout sustainability remains less comfortable than the higher-ranked dividend names.",
      "buyLow": 15,
      "buyHigh": 16.5,
      "buyYieldLow": 3.39,
      "buyYieldHigh": 3.73,
      "zoneStatus": "above",
      "allocation": 1,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=139",
      "dividendUrl": "https://www.jamstockex.com/?tag=SVL",
      "sa": "https://stockanalysis.com/quote/jmse/SVL/",
      "source": "JSE",
      "ytd": -10.79,
      "volume": 14724,
      "sector": "Consumer / Gaming & Entertainment",
      "score": 69
    },
    {
      "rank": 53,
      "ticker": "SRFJMD",
      "company": "Sygnus Real Estate Finance",
      "sector": "Real Estate",
      "price": 7.93,
      "priceDate": "2026-08-19 • JSE",
      "dayJmd": -1.27,
      "dayPct": -13.8,
      "w1": -17.68,
      "m1": -21.01,
      "ytd": null,
      "m3": -26.57,
      "m6": null,
      "y1": null,
      "ttmDps": null,
      "trailingYield": null,
      "latestDividend": null,
      "exDate": "N/A",
      "recordDate": "N/A",
      "payDate": "N/A",
      "dividendStatus": "Dividend review pending",
      "rating": "WATCH",
      "ratingClass": "hold",
      "reason": "Headline Deep Value / Earnings-Quality Risk • score 63. Weekly master-universe research baseline; daily price/history refresh follows.",
      "buyLow": 8,
      "buyHigh": 10,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "below",
      "allocation": 63,
      "jse": "https://www.jamstockex.com/trading/instruments/?instrument=1600118",
      "dividendUrl": "https://www.jamstockex.com/?tag=SRFJMD",
      "sa": "https://stockanalysis.com/quote/jmse/SRFJMD/",
      "source": "JSE",
      "performanceSource": "SA",
      "score": 63
    }
  ]
};
