window.JSE_DASHBOARD_DATA = {
  "updated": "August 18, 2026",
  "priceLabel": "Latest available / SA delayed where JSE unavailable",
  "stocks": [
    {
      "rank": 1,
      "ticker": "GK",
      "company": "GraceKennedy Limited",
      "price": 74.95,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.05,
      "dayPct": -0.07,
      "w1": -1.13,
      "m1": -1.38,
      "m3": 4.83,
      "m6": 5.25,
      "y1": 7.07,
      "performanceSource": "SA",
      "ttmDps": 2.37,
      "trailingYield": 3.16,
      "forwardYield": null,
      "latestDividend": 0.7,
      "exDate": "Upcoming",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 21, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Strong Buy",
      "ratingClass": "buy",
      "reason": "Best overall mix of business quality, sensible valuation and dividend coverage.",
      "buyLow": 70,
      "buyHigh": 76,
      "buyYieldLow": 3.12,
      "buyYieldHigh": 3.39,
      "zoneStatus": "in",
      "allocation": 16,
      "jse": "https://www.jamstockex.com/?tag=GK",
      "dividendUrl": "https://www.jamstockex.com/?tag=GK",
      "sa": "https://stockanalysis.com/quote/jmse/GK/",
      "source": "SA"
    },
    {
      "rank": 2,
      "ticker": "SJ",
      "company": "Sagicor Group Jamaica Limited",
      "price": 41,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.67,
      "dayPct": -1.61,
      "w1": -0.24,
      "m1": 5.67,
      "m3": -1.91,
      "m6": 2.5,
      "y1": 2.86,
      "performanceSource": "SA",
      "ttmDps": 1.78,
      "trailingYield": 4.34,
      "forwardYield": null,
      "latestDividend": 0.89,
      "exDate": "Apr 14, 2026",
      "recordDate": "Apr 14, 2026",
      "payDate": "May 6, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Strong dividend history and attractive actual trailing income support accumulation near the buy-zone ceiling, though recent earnings softness warrants monitoring.",
      "buyLow": 36,
      "buyHigh": 41,
      "buyYieldLow": 4.34,
      "buyYieldHigh": 4.94,
      "zoneStatus": "in",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/?tag=SJ",
      "dividendUrl": "https://www.jamstockex.com/?tag=SJ",
      "sa": "https://stockanalysis.com/quote/jmse/SJ/",
      "source": "SA"
    },
    {
      "rank": 3,
      "ticker": "SEP",
      "company": "Seprod Limited",
      "price": 74.99,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": 3.89,
      "dayPct": 5.47,
      "w1": 0.27,
      "m1": 3.01,
      "m3": -7.43,
      "m6": -7.16,
      "y1": -9.45,
      "performanceSource": "SA",
      "ttmDps": 1.82,
      "trailingYield": 2.55,
      "forwardYield": null,
      "latestDividend": 0.605,
      "exDate": "May 15, 2026",
      "recordDate": "May 15, 2026",
      "payDate": "Jun 5, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Low payout and strong earnings capacity support selective buying, but the price is at the upper edge of the accumulation range.",
      "buyLow": 68,
      "buyHigh": 75,
      "buyYieldLow": 2.43,
      "buyYieldHigh": 2.68,
      "zoneStatus": "in",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/?tag=SEP",
      "dividendUrl": "https://www.jamstockex.com/?tag=SEP",
      "sa": "https://stockanalysis.com/quote/jmse/SEP/",
      "source": "SA"
    },
    {
      "rank": 4,
      "ticker": "NCBFG",
      "company": "NCB Financial Group Limited",
      "price": 69.95,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.55,
      "dayPct": -0.78,
      "w1": -4.59,
      "m1": -4.46,
      "m3": 33.94,
      "m6": 60.11,
      "y1": 68.2,
      "performanceSource": "SA",
      "ttmDps": 2,
      "trailingYield": 2.86,
      "forwardYield": null,
      "latestDividend": 0.5,
      "exDate": "Aug 28, 2026",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 11, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "The pullback improves entry value while the current dividend remains comfortably covered relative to the recovery in profitability.",
      "buyLow": 64,
      "buyHigh": 70,
      "buyYieldLow": 2.86,
      "buyYieldHigh": 3.13,
      "zoneStatus": "in",
      "allocation": 14,
      "jse": "https://www.jamstockex.com/?tag=NCBFG",
      "dividendUrl": "https://www.jamstockex.com/?tag=NCBFG",
      "sa": "https://stockanalysis.com/quote/jmse/NCBFG/",
      "source": "SA"
    },
    {
      "rank": 5,
      "ticker": "CAR",
      "company": "Carreras Limited",
      "price": 34.05,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.05,
      "dayPct": -0.15,
      "w1": 0.26,
      "m1": 10.36,
      "m3": 51.65,
      "m6": 68.76,
      "y1": 98.2,
      "performanceSource": "SA",
      "ttmDps": 1.35,
      "trailingYield": 3.96,
      "forwardYield": null,
      "latestDividend": 0.41,
      "exDate": "Aug 28, 2026",
      "recordDate": "Aug 28, 2026",
      "payDate": "Sep 17, 2026",
      "dividendStatus": "Current declaration",
      "rating": "Buy/Accumulate",
      "ratingClass": "buy",
      "reason": "Strong current income, but a high payout and sharp recent rerating argue against chasing above the dividend buy zone.",
      "buyLow": 29,
      "buyHigh": 32,
      "buyYieldLow": 4.22,
      "buyYieldHigh": 4.66,
      "zoneStatus": "above",
      "allocation": 11,
      "jse": "https://www.jamstockex.com/?tag=CAR",
      "dividendUrl": "https://www.jamstockex.com/?tag=CAR",
      "sa": "https://stockanalysis.com/quote/jmse/CAR/",
      "source": "SA"
    },
    {
      "rank": 6,
      "ticker": "LASM",
      "company": "Lasco Manufacturing Limited",
      "price": 8.13,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.07,
      "dayPct": -0.85,
      "w1": 2.5,
      "m1": 24.24,
      "m3": 27.13,
      "m6": 29.13,
      "y1": 32.47,
      "performanceSource": "SA",
      "ttmDps": 0.19,
      "trailingYield": 2.32,
      "forwardYield": null,
      "latestDividend": 0.2,
      "exDate": "Aug 14, 2026",
      "recordDate": "Aug 14, 2026",
      "payDate": "Aug 28, 2026",
      "dividendStatus": "Dividend increased 5.3% YoY",
      "rating": "Hold / Buy dips",
      "ratingClass": "hold",
      "reason": "The dividend increased and coverage is strong, but a 23% one-month rally leaves the share price materially above the preferred income entry zone.",
      "buyLow": 6.25,
      "buyHigh": 7,
      "buyYieldLow": 2.71,
      "buyYieldHigh": 3.04,
      "zoneStatus": "above",
      "allocation": 8,
      "jse": "https://www.jamstockex.com/?tag=LASM",
      "dividendUrl": "https://www.jamstockex.com/?tag=LASM",
      "sa": "https://stockanalysis.com/quote/jmse/LASM/",
      "source": "SA"
    },
    {
      "rank": 7,
      "ticker": "KW",
      "company": "Kingston Wharves Limited",
      "price": 33.5,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.8,
      "dayPct": -2.33,
      "w1": -2.11,
      "m1": -6.41,
      "m3": -10.28,
      "m6": -5.74,
      "y1": 3.09,
      "performanceSource": "SA",
      "ttmDps": 0.7,
      "trailingYield": 2.04,
      "forwardYield": null,
      "latestDividend": 0.26,
      "exDate": "Jul 16, 2026",
      "recordDate": "Jul 16, 2026",
      "payDate": "Aug 14, 2026",
      "dividendStatus": "Paid",
      "rating": "Hold / Buy dips",
      "ratingClass": "hold",
      "reason": "Strong operating growth and dividend coverage, but the current yield remains modest and a lower entry price would improve income return.",
      "buyLow": 29,
      "buyHigh": 32,
      "buyYieldLow": 2.19,
      "buyYieldHigh": 2.41,
      "zoneStatus": "above",
      "allocation": 7,
      "jse": "https://www.jamstockex.com/?tag=KW",
      "dividendUrl": "https://www.jamstockex.com/?tag=KW",
      "sa": "https://stockanalysis.com/quote/jmse/KW/",
      "source": "SA"
    },
    {
      "rank": 8,
      "ticker": "LASD",
      "company": "Lasco Distributors Limited",
      "price": 3.33,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": -0.11,
      "dayPct": -3.2,
      "w1": -13.17,
      "m1": -6.06,
      "m3": 2.99,
      "m6": -8.82,
      "y1": -11.43,
      "performanceSource": "SA",
      "ttmDps": 0.12,
      "trailingYield": 3.49,
      "forwardYield": null,
      "latestDividend": 0.09,
      "exDate": "Aug 14, 2026",
      "recordDate": "Aug 14, 2026",
      "payDate": "Aug 28, 2026",
      "dividendStatus": "Dividend cut 25% YoY",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "The yield remains useful, but the latest annual dividend fell from J$0.12 to J$0.09 and earnings remain softer, reducing dividend-growth appeal.",
      "buyLow": 2.85,
      "buyHigh": 3.1,
      "buyYieldLow": 3.87,
      "buyYieldHigh": 4.21,
      "zoneStatus": "above",
      "allocation": 6,
      "jse": "https://www.jamstockex.com/?tag=LASD",
      "dividendUrl": "https://www.jamstockex.com/?tag=LASD",
      "sa": "https://stockanalysis.com/quote/jmse/LASD/",
      "source": "SA"
    },
    {
      "rank": 9,
      "ticker": "BIL",
      "company": "Barita Investments Limited",
      "price": 67.99,
      "priceDate": "Aug 14, 2026 • SA delayed",
      "dayJmd": 0.99,
      "dayPct": 1.48,
      "w1": -0.31,
      "m1": -4.72,
      "m3": -4.73,
      "m6": -6.1,
      "y1": -7.43,
      "performanceSource": "SA",
      "ttmDps": 2.398,
      "trailingYield": 3.53,
      "forwardYield": null,
      "latestDividend": 2.398,
      "exDate": "Oct 17, 2025",
      "recordDate": "Oct 17, 2025",
      "payDate": "Oct 31, 2025",
      "dividendStatus": "No new declaration",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "The yield is useful and earnings have recovered, but valuation remains relatively demanding and a fresher dividend declaration is needed.",
      "buyLow": 60,
      "buyHigh": 65,
      "buyYieldLow": 3.69,
      "buyYieldHigh": 4,
      "zoneStatus": "above",
      "allocation": 4,
      "jse": "https://www.jamstockex.com/?tag=BIL",
      "dividendUrl": "https://www.jamstockex.com/?tag=BIL",
      "sa": "https://stockanalysis.com/quote/jmse/BIL/",
      "source": "SA"
    },
    {
      "rank": 10,
      "ticker": "JMMBGL",
      "company": "JMMB Group Limited",
      "price": 14.7,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": 0.2,
      "dayPct": 1.38,
      "w1": 0.73,
      "m1": -1.31,
      "m3": -4.43,
      "m6": -11.18,
      "y1": -20.57,
      "performanceSource": "SA",
      "ttmDps": 0.2,
      "trailingYield": 1.38,
      "forwardYield": null,
      "latestDividend": 0.35,
      "exDate": "Jul 29, 2026",
      "recordDate": "Jul 29, 2026",
      "payDate": "Sep 3, 2026",
      "dividendStatus": "Payment pending",
      "rating": "Watch/Wait",
      "ratingClass": "hold",
      "reason": "Price is inside the buy zone, but earnings and dividend consistency remain materially weaker than the higher-ranked names.",
      "buyLow": 13.5,
      "buyHigh": 15,
      "buyYieldLow": null,
      "buyYieldHigh": null,
      "zoneStatus": "in",
      "allocation": 3,
      "jse": "https://www.jamstockex.com/?tag=JMMBGL",
      "dividendUrl": "https://www.jamstockex.com/?tag=JMMBGL",
      "sa": "https://stockanalysis.com/quote/jmse/JMMBGL/",
      "source": "SA"
    },
    {
      "rank": 11,
      "ticker": "TJH",
      "company": "TransJamaican Highway Limited",
      "price": 11.25,
      "priceDate": "Aug 18, 2026 • SA delayed",
      "dayJmd": -0.24,
      "dayPct": -2.09,
      "w1": 4.45,
      "m1": 22.28,
      "m3": 57.56,
      "m6": 67.91,
      "y1": 204.05,
      "performanceSource": "SA",
      "ttmDps": 0.294,
      "trailingYield": 2.61,
      "forwardYield": null,
      "latestDividend": 0.16503,
      "exDate": "Apr 7, 2026",
      "recordDate": "Apr 7, 2026",
      "payDate": "Apr 28, 2026",
      "dividendStatus": "No new declaration",
      "rating": "Hold / Wait",
      "ratingClass": "hold",
      "reason": "Excellent operating and capital-appreciation momentum, but the 22.28% one-month and 204.05% one-year rise has compressed the dividend yield for new buyers.",
      "buyLow": 8.5,
      "buyHigh": 9.75,
      "buyYieldLow": 3.02,
      "buyYieldHigh": 3.46,
      "zoneStatus": "above",
      "allocation": 2,
      "jse": "https://www.jamstockex.com/?tag=TJH",
      "dividendUrl": "https://www.jamstockex.com/?tag=TJH",
      "sa": "https://stockanalysis.com/quote/jmse/TJH/",
      "source": "SA"
    },
    {
      "rank": 12,
      "ticker": "SVL",
      "company": "Supreme Ventures Limited",
      "price": 17.9,
      "priceDate": "Aug 17, 2026 • SA delayed",
      "dayJmd": 0.31,
      "dayPct": 1.78,
      "w1": -0.28,
      "m1": -4.37,
      "m3": 6.06,
      "m6": -0.85,
      "y1": -9.09,
      "performanceSource": "SA",
      "ttmDps": 0.56,
      "trailingYield": 3.14,
      "forwardYield": null,
      "latestDividend": 0.2635,
      "exDate": "Aug 17, 2026",
      "recordDate": "Aug 17, 2026",
      "payDate": "Sep 30, 2026",
      "dividendStatus": "Ex-dividend passed",
      "rating": "Hold",
      "ratingClass": "hold",
      "reason": "Income is acceptable and earnings have improved, but payout sustainability remains less comfortable than the higher-ranked dividend names.",
      "buyLow": 15,
      "buyHigh": 16.5,
      "buyYieldLow": 3.39,
      "buyYieldHigh": 3.73,
      "zoneStatus": "above",
      "allocation": 1,
      "jse": "https://www.jamstockex.com/?tag=SVL",
      "dividendUrl": "https://www.jamstockex.com/?tag=SVL",
      "sa": "https://stockanalysis.com/quote/jmse/SVL/",
      "source": "SA"
    }
  ]
};
