(() => {
  const DATA = window.JSE_DASHBOARD_DATA;
  if (!DATA?.stocks) return;
  const byTicker = new Map(DATA.stocks.map(s => [String(s.ticker).toUpperCase(), s]));
  const parseDate = v => { if (!v) return null; const d = new Date(`${v}T23:59:59`); return Number.isNaN(d.valueOf()) ? null : d; };
  const isFuturePay = s => { const d=parseDate(s.payDate); return d ? d.getTime() > Date.now() : false; };
  const ageMonths = s => { const d = parseDate(s.payDate); if (!d || isFuturePay(s)) return null; return (Date.now() - d.getTime()) / (1000 * 60 * 60 * 24 * 30.44); };
  const recency = s => { if(isFuturePay(s))return 'next'; const m = ageMonths(s); if (m == null) return 'unknown'; if (m > 18) return 'stale'; if (m > 12) return 'aging'; return 'current'; };
  const label = s => { const r=recency(s); if(r==='next')return{cls:'div-recency current',title:'Next dividend pay',text:`Next dividend pay ${s.payDate||'N/A'}`};if(r==='stale')return{cls:'div-recency stale',title:'Last dividend paid',text:`Dividend inactive / stale • last paid ${s.payDate||'N/A'}`};if(r==='aging')return{cls:'div-recency aging',title:'Last dividend paid',text:`Dividend recency warning • last paid ${s.payDate||'N/A'}`};if(r==='current')return{cls:'div-recency current',title:'Last dividend paid',text:`Last dividend paid ${s.payDate||'N/A'}`};return{cls:'div-recency unknown',title:'Dividend pay date',text:'Dividend pay date N/A'}; };
  function addCardRecency(){document.querySelectorAll('.stock-card').forEach(card=>{const ticker=card.querySelector('h3')?.textContent?.trim().toUpperCase(),s=byTicker.get(ticker);if(!s)return;let row=card.querySelector('.dividend-recency-row');const latestRow=[...card.querySelectorAll('.metric-row')].find(r=>r.textContent.includes('Latest dividend'));if(!latestRow)return;const l=label(s);if(!row){latestRow.insertAdjacentHTML('afterend',`<div class="metric-row dividend-recency-row"><span></span><strong></strong></div>`);row=latestRow.nextElementSibling;}row.querySelector('span').textContent=l.title;const strong=row.querySelector('strong');strong.className=l.cls;strong.textContent=`${s.payDate||'N/A'}${recency(s)==='stale'?' • STALE':''}`;if(recency(s)==='stale'&&!card.querySelector('.dividend-stale-note'))latestRow.insertAdjacentHTML('afterend','<div class="dividend-stale-note">Historical yield may overstate current income: no recent dividend payment detected.</div>');});}
  function addFreshCapitalRecency(){document.querySelectorAll('.fresh-card').forEach(card=>{const ticker=card.querySelector('.fresh-title strong')?.textContent?.trim().toUpperCase(),s=byTicker.get(ticker);if(!s)return;const l=label(s),footer=card.querySelector('.fresh-secondary')||card.querySelector('.fresh-footer');if(!footer)return;let el=card.querySelector('.fresh-dividend-recency');if(!el){footer.insertAdjacentHTML('beforebegin','<div class="fresh-dividend-recency"></div>');el=footer.previousElementSibling;}el.className=`fresh-dividend-recency ${l.cls}`;el.textContent=`${l.text}${recency(s)==='stale'?' • income thesis weakened':''}`;});}
  function apply(){addCardRecency();addFreshCapitalRecency();}
  window.addEventListener('load',apply);window.addEventListener('storage',apply);document.addEventListener('click',()=>setTimeout(apply,40));new MutationObserver(()=>apply()).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});
  if(!document.querySelector('script[data-focus-typeahead]')){const s=document.createElement('script');s.dataset.focusTypeahead='true';s.src=`focus-typeahead.js?v=${Date.now()}`;s.onload=()=>{if(!document.querySelector('script[data-multi-focus]')){const m=document.createElement('script');m.dataset.multiFocus='true';m.src=`multi-focus-ui.js?v=${Date.now()}`;document.head.appendChild(m);}};document.head.appendChild(s);}
})();