(() => {
  const DATA=window.JSE_DASHBOARD_DATA;
  if(!DATA?.stocks)return;
  const byTicker=new Map(DATA.stocks.map(s=>[String(s.ticker).toUpperCase(),s]));
  const n=v=>v==null||!Number.isFinite(Number(v))?null:Number(v);
  const fmt=(v,d=2)=>n(v)==null?'N/A':n(v).toFixed(d);
  const pct=v=>{const x=n(v);return x==null?'N/A':`${x>0?'+':''}${x.toFixed(1)}%`;};
  const tone=v=>n(v)==null?'neutral':n(v)>0?'positive':n(v)<0?'negative':'neutral';
  const curPrefix=c=>c==='TTD'?'TT$':c==='USD'?'US$':'J$';
  const ttmMoney=s=>{const x=n(s.ttmDps);if(x==null)return'N/A';const c=s.ttmDpsCurrency||'JMD';const digits=Math.abs(x)<0.01?6:2;return`${curPrefix(c)}${x.toFixed(digits)}`;};
  const money=(v,c='JMD')=>{const x=n(v);if(x==null)return'N/A';const p=curPrefix(c);const a=Math.abs(x);let z=a,s='';if(a>=1e12){z=a/1e12;s='T'}else if(a>=1e9){z=a/1e9;s='B'}else if(a>=1e6){z=a/1e6;s='M'}else if(a>=1e3){z=a/1e3;s='K'}const d=z>=100?0:z>=10?1:2;return`${x<0?'-':''}${p}${z.toFixed(d)}${s}`;};
  const HELP={eps:'Earnings per share (EPS) is trailing net income attributable to each share. It connects company earnings to the share price and is the denominator used in P/E.',epsGrowth:'EPS growth shows how earnings per share changed versus the comparable prior period. Positive growth can support valuation and dividend capacity; unusually large changes should be interpreted with the underlying earnings trend.',pe:'Price-to-earnings (P/E) shows how much investors are paying for each dollar of trailing earnings. A low P/E can indicate value, but can also reflect weak or declining earnings.',profit:'Net profit is trailing net income. It shows the absolute earnings generated by the company, while EPS adjusts those earnings for the share count.',profitGrowth:'Net profit growth shows whether total company earnings are expanding or contracting versus the comparable prior period.'};
  function help(label,key){return`<span class="earnings-label">${label}<button type="button" class="expert-help" aria-label="Explain ${label}" data-tooltip="${HELP[key]}">?</button></span>`;}
  function strip(s){const items=[];if(n(s.epsTtm)!=null)items.push(`<div class="earnings-item">${help('EPS (TTM)','eps')}<strong>${fmt(s.epsTtm,2)}</strong></div>`);if(n(s.epsGrowth)!=null)items.push(`<div class="earnings-item">${help('EPS growth','epsGrowth')}<strong class="${tone(s.epsGrowth)}">${pct(s.epsGrowth)}</strong></div>`);if(n(s.pe)!=null)items.push(`<div class="earnings-item">${help('P/E','pe')}<strong>${fmt(s.pe,2)}×</strong></div>`);if(n(s.netIncomeTtm)!=null)items.push(`<div class="earnings-item">${help('Net profit (TTM)','profit')}<strong>${money(s.netIncomeTtm,s.statisticsCurrency)}</strong></div>`);if(n(s.netIncomeGrowth)!=null)items.push(`<div class="earnings-item">${help('Profit growth','profitGrowth')}<strong class="${tone(s.netIncomeGrowth)}">${pct(s.netIncomeGrowth)}</strong></div>`);return items.length?`<div class="earnings-strip"><div class="earnings-title">Earnings</div>${items.join('')}</div>`:'';}
  function compactCardRows(s){return [
    `<div class="metric-row compact-fundamental-row" data-card-fundamental="epsg"><span>EPS Growth</span><strong class="${tone(s.epsGrowth)}">${pct(s.epsGrowth)}</strong></div>`,
    `<div class="metric-row compact-fundamental-row" data-card-fundamental="pe"><span>P/E</span><strong>${n(s.pe)==null?'N/A':fmt(s.pe,2)+'×'}</strong></div>`,
    `<div class="metric-row compact-fundamental-row" data-card-fundamental="ttm"><span>TTM DPS</span><strong>${ttmMoney(s)}</strong></div>`
  ].join('');}
  function decorateCards(){document.querySelectorAll('.stock-card').forEach(card=>{card.querySelector('.earnings-strip')?.remove();card.querySelectorAll('.compact-fundamental-row').forEach(el=>el.remove());const t=card.querySelector('h3')?.textContent?.trim().toUpperCase(),s=byTicker.get(t);if(!s)return;const rows=[...card.querySelectorAll('.metric-row')];const trailing=rows.find(r=>/Trailing yield/i.test(r.textContent));const lastTrend=rows.find(r=>/12 Months/i.test(r.textContent));const anchor=trailing||lastTrend;if(anchor)anchor.insertAdjacentHTML(trailing?'beforebegin':'afterend',compactCardRows(s));});}
  function decorateFresh(){document.querySelectorAll('.fresh-card').forEach(card=>{card.querySelector('.earnings-strip')?.remove();const t=card.querySelector('.fresh-title strong')?.textContent?.trim().toUpperCase(),s=byTicker.get(t);if(!s)return;const html=strip(s);if(!html)return;const cash=card.querySelector('.cash-health-strip'),badges=card.querySelector('.investor-badges');if(cash)cash.insertAdjacentHTML('afterend',html);else if(badges)badges.insertAdjacentHTML('afterend',html);});}
  function overallFromCard(card,s){const m=card.textContent.match(/Overall\s*(\d+(?:\.\d+)?)/i);const v=m?Number(m[1]):Number(s?.score);return Number.isFinite(v)?v:0;}
  function ratingTier(s){const r=`${s?.ratingClass||''} ${s?.rating||''}`.toLowerCase();if(/avoid|sell/.test(r))return 1;if(/buy|accumulate/.test(r))return 3;return 2;}
  function entryMultiplier(s){return s?.zoneStatus==='below'?1.10:s?.zoneStatus==='in'?1.00:0.80;}
  function rerankFreshCapital(){
    const list=document.getElementById('rankingList');if(!list)return;
    const cards=[...list.querySelectorAll(':scope > .fresh-card')];if(cards.length<2)return;
    const ranked=cards.map(card=>{const ticker=card.querySelector('.fresh-title strong')?.textContent?.trim().toUpperCase(),s=byTicker.get(ticker);const overall=overallFromCard(card,s),mult=entryMultiplier(s),freshScore=overall*mult;return{card,ticker,s,overall,mult,freshScore,tier:ratingTier(s)};}).sort((a,b)=>b.tier-a.tier||b.freshScore-a.freshScore||b.overall-a.overall||a.ticker.localeCompare(b.ticker));
    ranked.forEach((x,i)=>{if(list.children[i]!==x.card)list.appendChild(x.card);const badge=x.card.querySelector('.fresh-rank');if(badge){const text=`#${i+1}`;if(badge.textContent!==text)badge.textContent=text;badge.title=`Dynamic Fresh Capital rank • Overall ${x.overall.toFixed(0)} × ${x.mult.toFixed(2)} entry adjustment = ${x.freshScore.toFixed(1)} • ${x.tier===3?'Buy-class':x.tier===2?'Hold-class':'Avoid-class'} priority`;badge.dataset.freshScore=x.freshScore.toFixed(1);}});
    const panel=document.getElementById('freshCapitalSection');const badge=panel?.querySelector('.panel-badge');if(badge&&badge.textContent!=='Dynamic: rating • score • entry')badge.textContent='Dynamic: rating • score • entry';
  }
  function headerIndex(head,label){return [...head.children].findIndex(x=>x.textContent.trim()===label);}
  function decorateTable(){
    const table=document.querySelector('#tableView table'),head=table?.querySelector('thead tr');if(!head)return;
    if(!head.querySelector('[data-earnings-col="pe"]')){
      const yieldTh=[...head.children].find(x=>x.textContent.trim()==='Yield');
      if(yieldTh){const thPe=document.createElement('th');thPe.dataset.earningsCol='pe';thPe.textContent='P/E';const thEg=document.createElement('th');thEg.dataset.earningsCol='epsg';thEg.textContent='EPS Growth';head.insertBefore(thPe,yieldTh);head.insertBefore(thEg,yieldTh);}
    }
    const ttmIdx=headerIndex(head,'TTM DPS');
    document.querySelectorAll('#stockTableBody tr').forEach(row=>{
      const t=row.querySelector('.ticker')?.textContent?.trim().toUpperCase(),s=byTicker.get(t);if(!s)return;
      if(!row.querySelector('[data-earnings-cell="pe"]')){
        const before=row.children[ttmIdx+1]||null;
        const pe=document.createElement('td');pe.dataset.earningsCell='pe';
        const eg=document.createElement('td');eg.dataset.earningsCell='epsg';
        if(before){row.insertBefore(pe,before);row.insertBefore(eg,before);}else{row.append(pe,eg);}
      }
      const pe=row.querySelector('[data-earnings-cell="pe"]'),eg=row.querySelector('[data-earnings-cell="epsg"]');
      pe.innerHTML=n(s.pe)==null?'<span class="neutral">N/A</span>':`<strong>${fmt(s.pe,2)}×</strong>`;
      eg.innerHTML=n(s.epsGrowth)==null?'<span class="neutral">N/A</span>':`<strong class="${tone(s.epsGrowth)}">${pct(s.epsGrowth)}</strong>`;
      if(ttmIdx>=0&&row.children[ttmIdx])row.children[ttmIdx].textContent=ttmMoney(s);
    });
  }
  function styles(){if(document.getElementById('earningsUiStyles'))return;const s=document.createElement('style');s.id='earningsUiStyles';s.textContent=`.earnings-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(130px,1fr));gap:7px;margin:10px 0;padding:9px;border:1px solid var(--border);background:var(--surface2);border-radius:12px}.earnings-title{grid-column:1/-1;color:var(--muted);font-size:.6rem;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.earnings-item{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:8px;padding:8px 9px;border:1px solid var(--border);background:var(--surface);border-radius:9px}.earnings-item strong{font-size:.7rem;white-space:nowrap}.earnings-label{display:inline-flex;align-items:center;gap:4px;color:var(--muted);font-size:.57rem;font-weight:700;line-height:1.2}.earnings-label .expert-help{width:14px;height:14px;min-width:14px;font-size:.48rem}.earnings-strip .positive,.compact-fundamental-row .positive{color:var(--green)}.earnings-strip .negative,.compact-fundamental-row .negative{color:var(--red)}.compact-fundamental-row{background:color-mix(in srgb,var(--surface2) 45%,transparent)}.compact-fundamental-row:first-of-type{margin-top:2px}.fresh-rank{cursor:help}@media(max-width:720px){.earnings-strip{grid-template-columns:repeat(2,minmax(0,1fr));padding:8px}.earnings-item{grid-template-columns:1fr;gap:4px}.earnings-item strong{font-size:.72rem}}`;document.head.appendChild(s);}
  let queued=false;function apply(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorateTable();decorateCards();decorateFresh();rerankFreshCapital();});}
  styles();apply();window.addEventListener('load',apply);window.addEventListener('storage',apply);new MutationObserver(m=>{if(m.some(x=>[...x.addedNodes].some(n=>n.nodeType===1)))apply();}).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});
})();